### ISSUE TITLE
error loading script in fast stable diffusion colab

### ISSUE THREAD

**Issue by Rymi2003** [DominikDoom/a1111-sd-webui-tagcomplete#104]
![image](https://user-images.githubusercontent.com/121863907/210341527-a8bf44a0-0c1b-498e-868c-ffebe0a19236.png)

it worked in in stable diffusion local,but not in colab.

**Comment by DominikDoom** [comment]
This is a reoccurring issue with fast-stablediffusion since they change the working directory mid-startup, which confuses the path comparison. As far as I'm aware I can't prevent that from my side, a small code edit is needed in the colab. Since the folder structure they use has changed multiple times since this issue first popped up and undone previous fixes, I'm not really sure what the current state is, so I can only tell you what worked for others before for now:

In the last code cell, try changing
```python
with capture.capture_output() as cap: 
  %cd /content/gdrive/MyDrive/sd/stablediffusion
```
to
```python
with capture.capture_output() as cap: 
  %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui
```
at this part close to the end:
![image](https://user-images.githubusercontent.com/34448969/210343986-b0ed94ea-e149-460a-9dc2-44cf154d4639.png)

See #67, #79 and https://github.com/TheLastBen/fast-stable-diffusion/issues/409 for more info.

**Comment by Rymi2003** [comment]
thankyou bro
