### ISSUE TITLE
Doesnt update when extensions are removed/renamed, even when webui is restarted

### ISSUE THREAD

**Issue by Flonixcorn** [DominikDoom/a1111-sd-webui-tagcomplete#106]
like in the title, it doesnt update when extensions are removed/renamed, even when webui is restarted had to remove emb.txt to get the removed ones out

**Comment by DominikDoom** [comment]
Embeddings are reloaded by the webui when the model is changed or the webui is closed and reopened (not when using the restart buttons in the UI). Since the new embedding system uses the internal webui embedding database instead of just the filenames to get them, they will not update otherwise. Also, after changing the model a restart is still required to update the embedding list stored by the browser for now.

A fresh close & restart should definitely reload them though, and I confirmed that on my system just now - removed embeddings weren't written to emb.txt afterward.

**Comment by DominikDoom** [comment]
Closing due to lack of feedback.
