### ISSUE TITLE
[Feature request] Link to tag wiki

### ISSUE THREAD

**Issue by kjhf** [DominikDoom/a1111-sd-webui-tagcomplete#109]
Sometimes a suggestion comes up that I am unfamiliar with. It would be good to include a link to Danbooru or e621 for that tag.
e.g. 1girl could have a [❔](https://danbooru.donmai.us/wiki_pages/1girl)

**Comment by DominikDoom** [comment]
This is the most realistic suggestion for now, and since parent tags or related tags are usually listed on the wiki, it would sorta cover #110 and #111 as well.

One tidbit is that I would like to make this an opt-in feature, since it would link to external sites which also often contain NSFW image examples directly on the wiki page. Another problem would be that it won't work for custom/uncommon tags which don't have a wiki page and I have no easy way to check if a wiki page exists for a given tag, so it would probably lead to some "This wiki page doesn't exist" links. But since danbooru itself also shows the ? for tags with empty wiki pages, it's more of a small inconvenience.

**Comment by kjhf** [comment]
thank you! And understood with the other feature requests :) Amazing stuff 🎉
