### ISSUE TITLE
[Feature request] Suggest related tags

### ISSUE THREAD

**Issue by kjhf** [DominikDoom/a1111-sd-webui-tagcomplete#110]
If accepting a tag, suggest related tags (these can often be found on the tag wiki)

**Comment by DominikDoom** [comment]
Danbooru has some time in December removed the directly accessible public caches for its dataset, meaning the only feasible way to get this information for now would be querying the related tags / implications using the danbooru API for each tag separately.
Since this would not work in the current offline-compatible setup and would require users to provide an API key, I don't plan to add this. It is also pretty out of scope since the user could just open the wiki page manually to find these and they have no importance to the autocompletion itself, only for tag discovery.
