### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by Labitchy** [DominikDoom/a1111-sd-webui-tagcomplete#114]
When I open a tab - using any browser - it crashes after 2-3 seconds. The terminal doesn't print anything, the page just start to slow down incredibly fast, to the point firefox asks: "This page is slowing down Firefox. To speed up your browser, stop this page." If I don't stop it, after 5-6 seconds or so all my tabs will freeze for about a minute or more. Then, all of the pages **excluding stable diffusion** will return to normal. The tab remains frozen indefinitely and if I try to interact w/ anything - doesn't work - it repeats the above process all over again. Terminal clean, one time I could open the inspector and it said: "Could load... X from /stable-diffusion-webui/extensions/tagcomplete" a couple of times.

I had the extension for a while and only after I updated both automatic and this extension it got this way. I did git pull the first time that I had the problem, moved the extension out the folder, it ran clean. I tried installing from scratch or via the tab UI, both led me to the same problem.

**Comment by DominikDoom** [comment]
This isn't really enough info for me to work with, but if you run it locally, the only thing I know will hang the page is if you use one of the full tag sets (so e621.csv or danbooru.csv) as an extra file, which is why I included a warning not to do that. You can check the config.json file in your webui root folder for that without launching it.

Other than that, I would need the full error message from the browser console.

**Comment by Labitchy** [comment]
![image](https://user-images.githubusercontent.com/123287479/213938136-f5f8499d-5a8f-4822-929b-ed32268cc6dd.png)
I installed today and its working so far, only getting this error from consoel

**Comment by DominikDoom** [comment]
If that error only appears after completing a word it's normal, this happens because I need to send an artificial event so the webui backend notices the text box changes. The internal binding expects an actual page element as an event source there so it throws an error, but it doesn't impede any functionality as far as I could tell.

I'll close this issue for now since it's working for you. Feel free to reopen it if the problem appears again.
