### ISSUE TITLE
It cannot be used without loading settings_interface

### ISSUE THREAD

**Issue by JLWLL** [DominikDoom/a1111-sd-webui-tagcomplete#116]
IF I comment this line
IN webui  modules/ui.py line 1765
tagcomplete cannot work.

`# interfaces += [(settings_interface, "Settings", "settings")]`

![image](https://user-images.githubusercontent.com/86763551/213995661-00035274-528d-437d-822c-6e4727f56eac.png)

Is it a bug or an optimization?
I want to using it without settings_interface
Thanks.

**Comment by DominikDoom** [comment]
The extension currently needs the settings interface since it watches / reacts to changes to the autocomplete related settings. I didn't consider that some might not use the settings interface, I can have a look at making it work without it later.

Just some small addendum: If you just want to prevent setting changes on a shared instance or similar, you can use the `--freeze-settings` command line argument when launching the webui instead of commenting out the line. In that case the extension should already work.

**Comment by JLWLL** [comment]
> The extension currently needs the settings interface since it watches / reacts to changes to the autocomplete related settings. I didn't consider that some might not use the settings interface, I can have a look at making it work without it later.
> 
> Just some small addendum: If you just want to prevent setting changes on a shared instance or similar, you can use the `--freeze-settings` command line argument when launching the webui instead of commenting out the line. In that case the extension should already work.

Thanks for your reply.
As you said, I will share the instance with others, and I don't want them to change some of the Settings, so my previous practice was comments.
'--freeze-settings' still displays the Settings interface after use, this is not good, for the front interface is not very beautiful, hope you can fix. Thank you very much!

**Comment by DominikDoom** [comment]
I have added some safety checks to skip listeners if the settings are missing.
One thing to note is that it will still work with anything you've added to the quicksettings bar, since that isn't reliant on the settings tab itself.

**Comment by JLWLL** [comment]
> I have added some safety checks to skip listeners if the settings are missing. One thing to note is that it will still work with anything you've added to the quicksettings bar, since that isn't reliant on the settings tab itself.

It work！！！！！
Thank you very much！！！
