### ISSUE TITLE
Chinese language pack request

### ISSUE THREAD

**Issue by qlyy-zsw** [DominikDoom/a1111-sd-webui-tagcomplete#120]
Dear Github Author,

I am a user of SD, and the updates of the interface has caused the prior version to be unusable. I do not quite understand the operation methods, so the new version cannot be translated into Chinese. If you could provide an additional Chinese translation package of the words and terms, I would be very grateful. 

Thank you for your time and effort.

**Comment by DominikDoom** [comment]
If you mean translated tags in general: #23 has files by another user. They both need "3-column translation format" checked to work:
![image](https://user-images.githubusercontent.com/34448969/216081911-1a6dd91d-b237-4b62-81f0-bf60d0346500.png)
Which should then work as expected:
![image](https://user-images.githubusercontent.com/34448969/216082182-bab795f9-7e6f-4f97-b486-b184bad2e23d.png)　![image](https://user-images.githubusercontent.com/34448969/216082325-d053597c-421b-4c1a-8c5f-8d7883daa267.png)

The difference between the settings is just that the new way has `<original>,<translation>` while the old one had
 `<original>,<placeholder>,<translation>` since it was based on another system originally.

**Comment by qlyy-zsw** [comment]
Thank you for the advice!
