### ISSUE TITLE
(Help) Tags autocomplete not working

### ISSUE THREAD

**Issue by KonstaVilkman** [DominikDoom/a1111-sd-webui-tagcomplete#123]
I installed the extension by pasting the git link to automatic1111 extension installer. Then reloaded everything but nothing.

**Comment by DominikDoom** [comment]
Have you done a complete close and restart? Some files might only get loaded on a fresh start.
Also try to refresh the site with CTRL+F5 to clear the browser cache, and make sure your webui is up to date.

If it's still not working after that, I will need more info like if there are error messages in the terminal or the browser console.

**Comment by KonstaVilkman** [comment]
[https://pastebin.com/gSN9HViS](url)
Here is my console error

**Comment by DominikDoom** [comment]
Well, your webui is too old. Lora support, which is what causes this error due to the one webui versions missing the attributes the script needs, was only introduced around two to three weeks ago. Update it to a more recent version or use a previous version of tag autocomplete as a workaround for now.

**Comment by KonstaVilkman** [comment]
Thank you for helping didn't know how to update it and looked it up.
For anyone having the same problem
Edit your webui-user.bat and add "git pull" and 
Mine looks like this:

> @echo off
> set PYTHON=
> set GIT=
> set VENV_DIR=
> set COMMANDLINE_ARGS= --xformers --opt-split-attention-v1 --autolaunch
> git pull
> call webui.bat
