### ISSUE TITLE
[Request] Toggle or customize keys for navigating list

### ISSUE THREAD

**Issue by TFWol** [DominikDoom/a1111-sd-webui-tagcomplete#127]
After updates, I usually go in and edit the script to remove capturing of **Home** and **End** keys since I use those to jump around the prompt as things pop up in my mind.
Here: https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/blob/c1fb4619a4fdf2fa872a43329b819cc1683f7ce0/javascript/tagAutocomplete.js#L688

Would you consider adding a way to choose the desired key or at least toggling it off/on?
I'd use the blacklist, but that disables the list entirely rather than just a couple of keys.

Editing the file is not too much of a hassle, but I'd thought I'd ask.

**Comment by DominikDoom** [comment]
Custom keys would have to be done by editing a local file (since I really don't want to bother with a custom UI or using the limited gradio settings inputs for it), which I guess would be feasible since they aren't likely changing much in the future.

I never really saw the need for it, since you just have to press Escape to close the autocomplete window if you want to jump in the text without completing something, which will make the following inputs behave normally again. But I understand it can be annoying due to muscle memory, so really I'll just add it now since it won't hinder anyone. And more customizability is always nice!

**Comment by DominikDoom** [comment]
I've added the custom key bindings feature, you can adjust them by editing the new `keymap.json` file in the extension's tags folder. So you can either set the bindings currently using Home/End to something else or disable them entirely by setting them to "None" or leaving the string empty.

**Comment by TFWol** [comment]
Works wonderfully, thanks!

**Comment by Kenqr** [comment]
The keymap.json file gets reset every time the extension is updated. Is there any way to keep my settings after updates?

**Comment by DominikDoom** [comment]
@Kenqr It seems the webui changed the update mechanism quite a while ago already from just git pull to a rebase, which removes local changes even if the file didn't change upstream. I wasn't aware of that, I will try to migrate the key map to the normal Gradio settings in a sensible way.

**Comment by DominikDoom** [comment]
@Kenqr I was able to add it successfully, you can now just edit the hotkeys (and colors) in the webui settings page. As long as you don't break the JSON in the textbox it will work the same as before.

**Comment by Kenqr** [comment]
Wow, that was fast.
Thanks!
