### ISSUE TITLE
Support to autocomplete extra networks from 3rd-party extensions

### ISSUE THREAD

**Issue by catboxanon** [DominikDoom/a1111-sd-webui-tagcomplete#162]
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

This extension uses the extra networks API to add another type of extra network. Unfortunately this means the identifier it uses is different (`lyco`), and more importantly this extension can no longer autocomplete any of these networks, as currently it only accounts for the built-in ones available in the web UI.

Do you have interest to support extensions like these? I could see something similar coming up again if [XTI embeds](https://github.com/kohya-ss/sd-scripts/pull/327) were to ever get support via another extension.

**Comment by DominikDoom** [comment]
> Do you have interest to support extensions like these? I could see something similar coming up again if https://github.com/kohya-ss/sd-scripts/pull/327 were to ever get support via another extension.

As a general answer to this question, of course! This is precisely why I majorly restructured the code in the v2.0.0 release, to make it much easier for PRs or myself to extend the base functionality if stuff like this comes up. Before it was all a monolithic file and started to get unmanageable, but now since it's all based on additional files that can add themselves to various execution queues, it's much easier to implement, check and fix since it's isolated. Sort of like an extensions lite system.
