### ISSUE TITLE
Follow symlinks

### ISSUE THREAD

**Issue by catboxanon** [DominikDoom/a1111-sd-webui-tagcomplete#168]
The web UI currently reads all extra networks recursively _and_ follows symlinks, something the `glob` module supports but I don't believe `pathlib` does yet. This can be verified by symlinking a directory, and comparing the list in the extra networks list compared to those returned by tagcomplete. A few examples here:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/5ab7f213bec2f816f9c5644becb32eb72c8ffb89/extensions-builtin/Lora/lora.py#L349-L352
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/5ab7f213bec2f816f9c5644becb32eb72c8ffb89/modules/hypernetworks/hypernetwork.py#L315
I know Gradio is pretty restrictive about anything outside of working directory, but I imagine if the extra networks list can read them fine then extensions could too.

**Comment by DominikDoom** [comment]
True, the Gradio restrictions only apply to the client side, so if the JavaScript part wants to load something. This isn't a problem for the list of hypernets and lora since they are written to a temp file. Only when those temp files are outside the root (so when the extensions dir itself is symlinked) there are problems.

I changed it to use glob similar to the webui implementation like you suggested, so it should follow them now.
