### ISSUE TITLE
Autocomplete of wildcards and embeddings is not shown.

### ISSUE THREAD

**Issue by toyxyz** [DominikDoom/a1111-sd-webui-tagcomplete#17]
Normal tag autocompletion works fine, but wildcards and embedding autocomplete are not shown. In tags/temp , wc.txt and emb.txt are listed normally. I wonder if there is something I am missing.

Version used: 1.5.1

**Comment by DominikDoom** [comment]
Since normal completion works, please try the following points:

- Check that useWildcards and useEmbeddings is true in the config
- Hit CTRL + F5 to refresh the page with a cleared cache, so the browser is forced to reload the files
- Check if the webui command line window or the browser console show any errors that seem related

**Comment by toyxyz** [comment]
Refresh with Ctrl+f5 and it works fine. thank you!

**Comment by DominikDoom** [comment]
Glad I could help!
Yeah, the cache seems to be a common problem, I should probably put a note about it in the README.
