### ISSUE TITLE
Support textareas inside accordions (on-demand loading)

### ISSUE THREAD

**Issue by re-unknown** [DominikDoom/a1111-sd-webui-tagcomplete#170]
As the title says, I don't know how to declare the base part of _textareas.js for extensions like Tiled Diffusion that are integrated at the bottom of the txt2img tab.
I tried "#tab_txt2img" and "#txt2img_script_container" but they did not work.
I'm not sure if this is a limitation of the extension or a problem with my description, so I'm submitting this just in case.

**Comment by re-unknown** [comment]
Or maybe the selector declaration was wrong, both "textbox" and "Textbox" were tried but did not make sense.
I am not very familiar with html and css, so I apologize if I am wrong.

**Comment by DominikDoom** [comment]
The base can be any type of element contained inside the gradio app container. This should always be the case for extensions that use the native UI instead of running their own backend and just inserting the iframe (like open-outpaint does for example).

So yes,  "#tab_txt2img" and "#txt2img_script_container" as the base parameter will work. The actual issue here is rather how Gradio handles accordions. The elements inside the accordion are only added to the page when it opens (and removed again when closed). That means, since the script runs at page load, it will find no text areas inside one of those since they literally aren't there yet. Other than that, the current method would work. Though as a general tip, that extension provides IDs so we can be much more specific in how we select the textareas. E.g. for the first region they are marked with "MD-t2i-0-prompt", "MD-t2i-0-neg-prompt", and so on.
So we can just do something like this:
```js
"tiled-diffusion": {
        "base": "#txt2img_script_container",
        "hasIds": true,
        "selectors": [
            "#MD-t2i-0-neg-prompt",
            "#MD-t2i-0-neg-prompt"
        ]
}
```

However, as I said this will not work yet due to said accordion.
The only real solution to that is to set up a listener that reacts to the accoridon opening, to then add the specified textareas on demand. I will see if I can add it.

**Comment by re-unknown** [comment]
Thanks for the validation!
At the same time I learned a lot, thank you!

**Comment by DominikDoom** [comment]
It was relatively painless to implement, luckily the JavaScript MutationObservers cover this scenario well.
 It will also add the observer to any new children that are accordions themselves, to ensure nested accordions work.

I also added tiled diffusion support along with it. The full config is this:
```js
"tiled-diffusion-t2i": {
    "base": "#txt2img_script_container",
    "hasIds": true,
    "onDemand": true,
    "selectors": [
        "[id^=MD-t2i][id$=prompt] textarea",
        "[id^=MD-t2i][id$=prompt] input[type='text']"
    ]
},
"tiled-diffusion-i2i": {
    "base": "#img2img_script_container",
    "hasIds": true,
    "onDemand": true,
    "selectors": [
        "[id^=MD-i2i][id$=prompt] textarea",
        "[id^=MD-i2i][id$=prompt] input[type='text']"
    ]
}
```
I had to split it up since the script containers have different IDs for t2i and i2i.
`onDemand` tells it to add the mutation observers to the accordions inside that base node.
For some reason, the negative prompts were done with a `<input>` element instead of `<textarea>`, which is why I search for both.

The other method for `"hasIds": false` with "Textbox" as the selector will work too, but it is always better to use IDs if possible since the Labels could change if the UI is translated, which would break the selection.
