### ISSUE TITLE
Whitelist/blacklist not working in webUI 1.1.1

### ISSUE THREAD

**Issue by Kiyos** [DominikDoom/a1111-sd-webui-tagcomplete#172]
webUI: 1.1.1 ([5ab7f21](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ab7f213bec2f816f9c5644becb32eb72c8ffb89))
Gradio: 3.28.1 (installed automatically)
a1111-sd-webui-tagcomplete: 4442cb7
Browser: Chrome 108

This is on a somewhat fresh installation (a couple days ago).
Neither whitelist nor blacklist won’t work. Autocompletion popup shows up with any model, completely ignoring all of the settings. I’ve tried inputting both name(s) and hash(es). Then I’ve noticed the following error in the JS console:

![tagAutocomplete js_line_879](https://user-images.githubusercontent.com/5103155/236366611-78c97f8c-fe86-461c-8a1c-b58dd177694c.png)

I’m guessing that `querySelector` doesn’t return what it’s supposed to return. And also the code branches to “Fallback for older versions” even though I have one of the recent ones.

**Comment by DominikDoom** [comment]
Thanks for bringing this to my attention, it was due to Gradio once again changing how they create dropdowns.
Hopefully with this fix it should work both on the newest, the old pre-3.22 update some people hang on to, and the intermediary solution that was used the last few weeks before the recent update to Gradio 3.28.

**Comment by Kiyos** [comment]
Ah, the joyous world of open source development where everything is constantly changing for no good reason 😉

**Comment by DominikDoom** [comment]
Well, it was definitely a good change, since in the intermediate version you couldn't filter the list by typing. And since it didn't use the native HTML select element anymore after 3.22, the browser wouldn't jump to that entry in the list when typing the starting letter either, which made finding a model in a long list very annoying. It just went unnoticed by me that the value of the dropdown was stored in a different place again due to this since I'm not using the blacklist myself most of the time.
