### ISSUE TITLE
Comma in LoRA filename corrupts hash cache and causes the extension to fail to load

### ISSUE THREAD

**Issue by r7vz9h3** [DominikDoom/a1111-sd-webui-tagcomplete#206]
The extension breaks and fails to load if you have a lora with a comma in its filename. As a workaround, don't have commas in lora names. I think the error was on this line, because it splits to more than 3 items:

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/blob/acb85d7bb1ad7c1854a98de63e05cfc2473eae5d/scripts/model_keyword_support.py#L20

Possibly to reproduce, you have to:
1. Add a comma to the middle of a lora filename.
2. Start WebUI with the extension on so it can regenerate the cache.
3. Restart WebUI so the extension attempts loading the now-incompatible cache.

**Comment by DominikDoom** [comment]
Yeah, I'll try fixing it by quoting the filenames and ignoring commas there.
If you don't mind me asking, what Loras are you using that have commas in the file name?
model-keyword itself also uses commas in its list, so it should cause problems there too if it were in it.

**Comment by r7vz9h3** [comment]
I edited some filenames myself and added commas. It's a very low priority issue, but I thought I'll report it.

**Comment by DominikDoom** [comment]
Well, at least under windows quotes are illegal in filenames, so I hope it will be a safer option compared to commas.
Other than that, there's really not much left to do except using some increasingly exotic separator or quote chars, but even then it's not for sure someone couldn't use it.
So I think it makes more sense to draw a line somewhere and just tell Linux users that run into issues to not use quotes in their filenames.

**Comment by DominikDoom** [comment]
With this it will load and display the loras themselves correctly.
However, adding custom keywords for those files through the model-keyword extension's UI will still not work out of the box, since it will write a line in the format
```csv
e3b0c442, test keywords|for|lora, lora with, comma filename.safetensors
```

So to get it to parse correctly and detect the keywords, you'd have to manually quote the filename part in the lora-keyword-user.txt file.

But for normal use and without trigger word completion it shouldn't cause issues anymore.
