### ISSUE TITLE
The plugin doesn't like Wildcard-Yaml 

### ISSUE THREAD

**Issue by nosdregamon** [DominikDoom/a1111-sd-webui-tagcomplete#209]
a1111-sd-webui-tagcomplete  allows for completion of Wildcards used by [sd-dynamic-prompts](https://github.com/adieyal/sd-dynamic-prompts).

The latter allows usage of [YAML-Files](https://github.com/adieyal/sd-dynamic-prompts/blob/main/docs/SYNTAX.md#yaml-files) however, actually using these file, it produces the following message(s) at startup...

```
Issue with tags found in example.yaml at item clothing
Issue with tags found in example.yaml at item artists

```
... and I can't use autocomplete on runtime.  Which is a shame, because there's some cool "libraries" [at civitai](https://civitai.com/models/115641/billions-of-constructions-standalone-extension-buildings-rooms-etc).

My guess is implementing yaml-files in sd-webui-tagcomplete would be quite complicated, but perhaps for a start it could ignore them?

**Comment by nosdregamon** [comment]
[example.zip](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/files/12198204/example.zip)

**Comment by DominikDoom** [comment]
Thanks for the example. This is actually a side effect of the already implemented yaml wildcard parser for https://github.com/Klokinator/Umi-AI, which expects a slightly different format. I didn't implement it myself, but included their pull request.

I was not aware that this causes issues with dynamic-prompts, I'll take a look and see if I can change it up so it works together with them or at least not show the error.

Normal functionality should however not be affected by this since they already are ignored, the error is not critical. While the yaml wildcards themselves obviously don't show up, everything else worked as normal when I tried it out just now.

**Comment by nosdregamon** [comment]
Thank you 👍 

The problem that it doesn't work at all, might then be a side-effect of a different extension in the mix. I'll try to narrow it down.

**Comment by DominikDoom** [comment]
I was able to add proper support for it!
It essentially treats each level of the yaml as if it were a normal wilcard file in a subfolder, so even the path traversal and peek into the subcategories will work like the normal wildcards, allowing you to step through and stop where you want.

Example with the building wildcards you linked:

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/1a1222cb-ff68-4adc-8e5e-3fb380c4df69

If the extension still doesn't work at all for you, I'd suggest opening a new issue since it's likely unrelated to this.
In that case also check if there are any errors in the browser console (CTRL-SHIFT-I).

**Comment by nosdregamon** [comment]
It works without additional errors. Thank you very much.
