### ISSUE TITLE
Autocomplete hidden beneath DOM as of latest webui dev branch commit (Gradio 3.39.0)

### ISSUE THREAD

**Issue by catboxanon** [DominikDoom/a1111-sd-webui-tagcomplete#213]
On the dev branch, the webui recently got bumped to Gradio 3.39.0. It seems like something changed with the DOM as now the autocomplete appears beneath the prompt area. 

![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/122327233/11519495-9dd7-4c91-95a7-1471d188c974)

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/362789a3793025c698fa42372fd66c3c4f2d6413

**Comment by DominikDoom** [comment]
Thanks for the heads up. This is a bit tricky since the new Gradio DOM now explicitly sets `overflow: hidden` on the prompt textbox parent div, whereas before it was `overflow: visible`. To spare me the headache of calculating vertical absolute positioning to fit below the textbox, I just nested it inside, instead of placing the popup in its own separate layer and shifting it around. This also helps by allowing a separate popup for each prompt textbox so less clearing/state recovery is required when switching between fields.

It is possible to explicitly override using something like
```css
div#txt2img_prompt[style] {
    overflow: visible !important;
}
```
or for a more generic selector to apply to all IDs ending in "prompt":
```css
div[id$=prompt][style] {
    overflow: visible !important;
}
```

But it needs to be very specific, since it might break other things if not carefully applied.
At least for the prompt textboxes themselves I couldn't find a difference, but since I am not familiar with the new / planned features on the dev branch I might overlook something. If you are more informed about that, I would appreciate if you could try that fix by adding it to your user.css and share if something doesn't look right.

**Comment by DominikDoom** [comment]
Yeah, that'll do it as well. I'm not that familiar with what's gradio and what's webui default styling, but this seems to also resolve an issue with the border style of the textbox I noticed just now.

With the fix, normal extruding border:
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/f1fe03cf-6077-4587-a7da-49cd09b65248)
Without:
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/ad65b669-af32-4d05-a489-31b7eeb57f6f)

I'll keep the issue open for now for visibility for other dev branch users until the PR gets merged.
