### ISSUE TITLE
prompt all in one extension support

### ISSUE THREAD

**Issue by JaysonPhoenix** [DominikDoom/a1111-sd-webui-tagcomplete#219]
eventho official support for prompt all in one was never stated here it still used to work in the extensions own prompt field and also in the label editing fields (when editing the prompt words you can drag around), and prompt all in one seems to have had tagcomplete support in mind since they mentioned it on their git which is how i actually even found your extension in the first place. but now at some point it stopped working for me in their extension a while ago, not sure if its a change on your side or on theirs but since they stated support for your extension and you didnt state it for theirs i thought i might ask here to add official support.

**Comment by DominikDoom** [comment]
I believe this is already fixed on their side https://github.com/Physton/sd-webui-prompt-all-in-one/commit/ec53d79bc65b3d7b987882debd6a2d5947c93980 and was caused by recent layout changes on my side to add the Lora previews. So check if there's an update available.

It wouldn't be a big issue to add their text boxes to the official list, but the problem is the load order. Since they don't use Gradio to construct their UI but add it through a script (similar to what I am doing myself), there's no guarantee that it already exists during my lookup. Depending on the amount of extensions a user has, the page load speed, etc., both my or their extension could load first and not find the other during its inital setup.

The only workaround for that, which they also use, is waiting and trying a few times until it works. In their case once after 1, 3, 5, 10, 20 and 30 seconds respectively. Aside from me doing the same thing on my side, there isn't really any way to add better support.

**Comment by JaysonPhoenix** [comment]
ahh yeah great, i really didnt update for 1 or maybe 2 days but the update just now really fixxd it, working just as good as before. thx for the quick response. 
its probably not that important if its stated on the official support list as long as you actually know of and support each other, thats good enough. eventho if it was stated there i wouldnt have had to ask and would have just figured if the problem is on your side you would fix it soon anyway just as i would figure he would if its on his side since he stated your extension in his readme. 

and yes i experienced the load order problem you described, that explains some issues with both extensions since i really have a lot extensions and some not using gradio but java or whatever, your extension usually kicks in at some point if not right at the bootup just as some features of other extensions like the translation of prompt all in one and throws errors till then. i actually even get a bunch of state errors in the console after the local server booted and the ui starts loading which looks like starting all the extensions takes too long and some timeout kind of stuff throws the errors then or like you described maybe they dont find each other or something and often i even have to restart the ui right after startup to make everything work, guess your explanation could be the explanation for that too then. 
anyways, thx and keep up the good work, love your new triggerword addition with model keyword support ;) cheers
