### ISSUE TITLE
[Suggestion] Can we have embeddings autocomplete without adding <e: before?

### ISSUE THREAD

**Issue by VL4DST3R** [DominikDoom/a1111-sd-webui-tagcomplete#230]
I can see this making sense for lora/lyco, since that's how they are defined inside the prompt and added via the extra networks menu, but embedding trigger words are written as-is, and it feels quite unintuitive to use lora/lyco-like syntax for them as well.

I know this was probably done for ease of implementation, but figured it's worth asking regardless for a nicer user experiece. Otherwise this extension is pretty much flawless in my book and I've been using it since its inception.

**Comment by DominikDoom** [comment]
This was initially left over from the original webui implementation. Embeddings used the <> syntax for quite a while, way before Loras were a thing. Although they quickly became optional (or even always were, not sure about that).

The main reason I keep them separate from normal tags nowadays is the difference in sorting.
Tags are sorted by their post count so that common tags are higher, but embeddings alphabetically.
Due to this they are hard to mix, similar to the extra tags they would need to be appended at the start or end. Since the embedding list can be much longer, this makes browsing for them hard if mixed with normal results.

Having said that, if you have "Show all results" enabled, I guess it could work. The tricky part there is just how to handle very long lists that get loaded on demand if the end is reached, since embeddings added to the end of the list would mess with the mechanism. But I'll have a look and see if I can work it out.

**Comment by VL4DST3R** [comment]
Can't you add embeddings to the top? For most people embeddings are words wildly different from the regular tokens one would use to describe images (for obvious reasons) so plonking the embeddings that match what the user is typing above regular tag autocomplete results would seem like the best approach.

Also yes, had show all results since i started using this.

**Comment by DominikDoom** [comment]
The issue there is mainly that a long embedding list could push the normal tags out of view if they come first and the search is short enough. Embeddings use a more generic matching rule, so it will also find the middle of words etc.
Even longer words can still be an issue, for example I have a lot of embeddings ending in "style", which completely push away normal results for things like "hair style". So a minimum length before including them won't really work either.

Implementation wise adding them to the start would definitely be easier, just not sure if it's a good tradeoff.

**Comment by VL4DST3R** [comment]
There is no control over how the searching behavior itself operates? I figured you could just look from the beginning of the word or following capitalization?

Funny enough I've read recently how Minecraft switched from its previous search where it would basically do what you describe, list results with the group of letters inside the word itself to now only display those that start with it.

**Comment by DominikDoom** [comment]
The normal tags do that, but not the embeddings / lora / lyco. Mainly since a lot of them use cryptic prefixes or add the creator name to make them distinctive from normal tags. Quite a few don't separate these at all from the rest of the word in the default name, which hinder the "only search for the start of the word" approach. And while I currently don't look at capitalization anyway, some of them do not even that and are all lowercase, all written together.

But I think I have found a good workaround for the issue. If the embeddings are included in the normal search, they will come first and push everything down, but not count towards the set maximum, so it will work without "Show all results". And to mitigate annoying scrolling, I added a new functionality to the End key. If the embedding list is particularly long, hitting End once will select the first non-embedding result, and on a second press the actual last result. So you can quickly jump between the sections using End and Home, even if they are part of the same list and differently sorted.

**Comment by DominikDoom** [comment]
Testing a few edge cases to make sure it works, should be ready in a few minutes.

**Comment by DominikDoom** [comment]
You can use it now by enabling this new option:
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/305a99f7-31a6-4289-85b2-0798b5a1935b)

**Comment by VL4DST3R** [comment]
Works great but have you toggled Active in txt2img to be off by default? I couldn't figure out why it wasn't working at all anymore and turns out it was entirely disabled.

Also quick question regarding list limit- is limiting the list really that big of an issue? What happens if you do indeed have hundreds of hits, is there really a substantial performance impact?

**Comment by VL4DST3R** [comment]
Thanks for the in-depth explanation. I also never needed it higher than 100 but good to know how it works. Thanks again for the fast response and addition!
