### ISSUE TITLE
UmiAI tag completition is not present for all tags

### ISSUE THREAD

**Issue by ctwrs** [DominikDoom/a1111-sd-webui-tagcomplete#238]
There seems to be an issue with how tags are gathered or parsed. A user on our discord had an issue with getting <[ezhair to autocomplete. This was working fine with an earlier version of tagcomplete (had locally a version from late 2022 I think but this should be a somewhat recent breakage because we didn't get any other reports about this).

**Comment by DominikDoom** [comment]
Seems like I accidentally broke it in 21de5fe, where I added a fix for Umi's yaml tag parsing throwing errors for other wildcard formats and added support for sd-dynamic-prompts wildcards.

The issue was a wrongly scoped variable, seems like the counter used to gather the Umi tags wasn't properly updated between files and essentially only wrote out the last one. Will push a fix soon.
