### ISSUE TITLE
wildcards no longer autocompleting

### ISSUE THREAD

**Issue by kenwud** [DominikDoom/a1111-sd-webui-tagcomplete#241]
ive tried deleting and reinstalling the extension, but "__" no longer autocompletes to the list of wildcards.. 
bit bash terminal into the extension directory command
`git reset --hard 5067afeee95b9a742742333c67837cd35d5d732a
`seems to have resolved the issue

**Comment by bWm-nubby** [comment]
I had the same experience. My wildcards are in the default location for [Tsukreya/Umi-AI-Wildcards](https://github.com/Tsukreya/Umi-AI-Wildcards)
I was previously using [Tsukreya/Umi-AI-debloat](https://github.com/Tsukreya/Umi-AI-debloat) and updated to the updated one when I noticed tagcomplete was unable to find them in the old extension.

**Comment by DominikDoom** [comment]
Can't reproduce, everything works like normal for me on the current version. I also tried it on a fresh installation with default settings, which made no difference.
I tried the wildcards @bWm-nubby mentioned, that works too.

Can you give me more details on your configuration? OS, Browser, Settings, etc.
Also, force-refresh the site using CTRL+F5, the issue might be old files in the wrong format being loaded instead of the new one required after the recent updates.
Check your browser console for errors (CTRL+SHIFT+I), if something goes wrong while loading it should be visible there. Also related to that, please enter `wildcardExtFiles` in the console to print out the variable and tell me if it has content.

**Comment by DominikDoom** [comment]
Scratch that, I was able to find an issue. The problem was not the third-party wildcards, but the old school `<webui root>/scripts/wildcards` missing. The extension accidentally tried to load these even if they didn't exist.

If you update to the newest version, it should work for you now.
