### ISSUE TITLE
Model keyword - partial load.

### ISSUE THREAD

**Issue by Symbiomatrix** [DominikDoom/a1111-sd-webui-tagcomplete#245]
Hello dom. Not sure if you've addressed this before, but I've attempted to load a faux model keyword extension with [this file](https://raw.githubusercontent.com/mix1009/model-keyword/main/lora-keyword.txt), and the load looks to have stopped at the hash 4752b0ae, apparently on account of it containing an unbalanced quote mark (graffiti"), with about 13k records. I see a couple quote escapes in parseCSV, not sure if they're supposed to handle this.

And if I may inquire, how do you handle model keyword's prevalent V1 hash collisions? I see something about going over multiple results but not quite clear on how the matching works, or if somewhere along the way the dict storage swallows it up. If it's not too much trouble, could you add a second custom file which reads V2 hashes instead of V1? That'd come in handy for me. Or perhaps it'd already work as long as the models are stored with the V2 hash?

**Comment by DominikDoom** [comment]
Thanks for telling me, This is indeed an error in the CSV parse logic. The non-regex parser I used respected quotes over newlines, so an unclosed quote meant everything after was interpreted as one line.
For multiline CSVs it would be very tricky, but since I only ever expect one-line-csvs for every use case right now, I can simply close the quote field if the end of a line is reached.

As for the collisions:
I account for them the same way model-keyword does. If there is more than one entry for a given hash, the lora name is compared as a secondary key. If no matching name is found, nothing is added to prevent unwanted keywords.
This means it will only work if the filename is the one model-keyword also knows.
You are correct that this is pretty fragile. But since model-keyword is mainly useful because of its large auto-updated list, V2 hash comparison doesn't have any benefit since the lists don't contain them. The reason model-keyword uses V1 is performance, they calculate and compare the hashes live before generation, so full SHA256 every time would be too slow. Don't know why they aren't using the webui's own cache file for V2 hashes, though.

However, if you are adding a manual list yourself anyway, adding the filename to clear up collisions shouldn't be a problem.
Or even better, use the "Edit metadata" feature of the webui in the corner of extra network cards, this will open a UI where you can add activation keywords directly for it. These will be stored in a json file with the same name next to the Lora, so no confusion potential. Tag autocomplete will always prefer these native declarations over model-keyword.

**Comment by Symbiomatrix** [comment]
Alright, thanks for the explanation.
I'm using vlad's fork, I think he has yet to add this metadata feature as there seems to be only description editing and metadata reading.

Actually, it's not exactly manual - I've written a small utility program which calculates the V1 + V2 hash for any new / updated models I add in the background (thus circumventing the issue of V2 hash's computation speed), grabs metadata from civitai's api, including keywords, and saves it all under a sqlite db. Optimally, if I could dump the contents of the db to such a V2 custom file, that'd be great - simple read write job. Given the current architecture, I'm modifying the hash code locally to read the db directly instead, hopefully that'll work. I'm no good with js and am only vaguely familiar with that side of the code so I don't think I could write something less hackish than this.

**Comment by DominikDoom** [comment]
Yeah, the reason for collisions in V1 is that the hash considers only the first few bytes of the file. Especially a lot of older loras and merges can fall victim to that as the first block can stay unmodified for quite a while. V2 uses the full file content, so only the collisions inherent to SHA256 are left, which are VERY unlikely.

If you already calculate V1 too, you can just append the name (with .safetensors included) in an additional column after the keywords, to match the model-keyword format of `model_hash, keyword, filename`. That should prevent all collisions, since obviously two files can't have the same name.

**Comment by Symbiomatrix** [comment]
Very well, I'll give that a shot.

> The only exception would be if you have two different Loras with the same name but in different folders, but that is a pretty bad idea anyway.

Heh, that's just what I was thinking. It actually has been somewhat of a problem since civitai stopped appending version names to models and letting authors name however they like, that's part of what the utility seeks out.
Should be alright, none of my models' filenames contain commas or other special chars. One of the more abominable side effects of lax naming.

**Comment by DominikDoom** [comment]
I tinkered a bit and got the V2 hash lookup to work. It uses the webui's internal hash methods, so it will only use cached hashes automatically.
As long as you add the same hash to the custom list that is in the webui cache file, it should work. You can also mix V1 and V2 hashes in the same file since they both simply act as dict keys.
Tag autocomplete will first try to find the V1 hash, but if there is no match it will now also try getting a V2 hash from the cache file using a new API endpoint.

**Comment by Symbiomatrix** [comment]
Fantastic, much obliged as always.
I think it might be preferable to prioritise V2 hashes since they're more accurate as we know. No risk of V1 / V2 mismatch as they're of different length. Granted, would double the time for model keyword's V1 results, but the lookup seems relatively short.

**Comment by DominikDoom** [comment]
I agree that V2 is generally better, but as long as model-keyword doesn't use it in its lists, it doesn't make much sense to make it the default. Most users will not go through the effort to make their own lists.

Speed isn't an issue either way, however the V2 request has to wait for the API while V1 has the preload time but then accesses the map in memory in $O(1)$ and should be pretty much instant. So technically V2 should be slower.
I haven't checked in practice though, it might very well be the case that V2 even with the network request is faster due to the cache lookup being in python while V1 is client-side in javascript.

**Comment by DominikDoom** [comment]
You misunderstood what I meant a bit, it has nothing to do with V1/V2 itself, just with the means of tag autocomplete accessing it. 
For the webui there is no difference between V1/V2 in practice, the cache is just needed because sha256 for files larger than a few megabytes is just too slow for doing it live every time. It is a local file, so if I want to use it, I either have to load the whole file or call the webui function that returns a hash from it (which is what I did). For calling that function I added a small internal API endpoint, similar to the other API stuff at the bottom of tag_autocomplete_helper.py

For V1 I can load the whole file in JS at the start since it only adds a small delay, but the webui cache file also includes a lot of other cached metadata. In my case it is ~13 MB, so the overhead of loading the whole thing was much bigger (and 95% of that data unneeded). So instead, I do the request live, which calls the internal method and only returns the hash.
It's also convenient since it is more robust against changes to the webui caching code, I don't need to parse the file itself and can use preexisting checks etc.

You are correct that network requests will always be magnitudes slower, as long as the data type in JS stays a dictionary/map. Loading the whole dict in js only has a higher memory cost.
Some other stuff like the tag autocompletion itself could get a performance increase by calculating it on the server though, since there is a lot more filtering going on in that case and not just a dict key lookup anymore.
