### ISSUE TITLE
A111 Refresh Button on Extra Networks hangs infinitely

### ISSUE THREAD

**Issue by Dasor92** [DominikDoom/a1111-sd-webui-tagcomplete#260]
After the last few updates the Lora Networks refresh button hangs, i tried reverting to commit 1a9157f in 21 september, and it doesn't hang. But it's still about 5 seconds slower than without extension. Can an option maybe be added to avoid Refresh button to affect autocomplete?

Tried with all other extensions disabled, same error.

**Comment by DominikDoom** [comment]
This is on normal A1111, right? Are you on the newest version there?

> But it's still about 5 seconds slower than without extension

This makes sense, as before the recent update it would manually re-scan for loras if you refresh. 
But now it uses the internal lora list instead of re-scanning, so it should not really have a speed impact anymore.
That's why I'm pretty confused about your issue. All tag autocomplete does when you press on that button is refresh its own lists, to avoid having to restart the webui to reflect changes. What I fixed for SD.Next that caused a hang there was essentially a gradio bug, but from what I've seen that never happened on normal A1111.

How many Loras, embeddings etc. do you have? It might be a strange race condition that only happens for large numbers, or something like that.

**Comment by Dasor92** [comment]
I’ll try again this evening the newest version of this extension and let you know, anyway yes, I have 2400 loras, so maybe it’s something that is correlated to that number.

**Comment by DominikDoom** [comment]
On which commits of the extension did you have the problem before? Originally I meant the webui version, but that of course is important too. A potential fix was added in 886704e35115ba4907d643c64c179b2ab476bf69, so one version back.

**Comment by DominikDoom** [comment]
Also, one thing you could try to see if it is related in case the issue persists:
Edit your local copy of `tag_autocomplete_helper.py` and change the last line of the [refresh_temp_files](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/blob/f840586b6bce9357cf0b52e8edaf98105b7453e7/scripts/tag_autocomplete_helper.py#L381-L385) function from `refresh_embeddings(force=True)` to `refresh_embeddings(force=False)`, then save the file and restart the webui. If that doesn't change anything, you could also try commenting it out completely by adding a `#` to the start of the line. The bug in SD.Next was related to embeddings, so I am more suspicious of them than of loras for now.
Sorry for having you test stuff like this, it's just near impossible to do myself since I don't have the hanging with my setup.

**Comment by Dasor92** [comment]
ok tried everything, i got it working by removing    the wildcards from the refresh function  inside #write_temp_files() i added a boolean: "skipwildcards" and when you call the function from the refresh it's True, when you call it from main it's false.
because the problem was write_to_temp_file('wce.txt', wildcards_ext) but only when it already exists 
i have the "civitai-wildcard-prompt-main" wildcards, that are 150.000 wildcards, so everytime you click refresh it tries to update that 35mb file and hangs indefinitely because i think it tries to do something with it. 
without that long wildcard it works fine.

**Comment by DominikDoom** [comment]
Ah, thank you very much for the in-depth testing! I will take a look if I can find an actual fix, but if not adding a compatibility option like you suggested is no problem.

**Comment by DominikDoom** [comment]
I actually still wasn't able to get it to hang, even though I used the same collection for testing. It did take noticeably longer, though. It might come down to file access speed, are you maybe using a HDD instead of an SDD?

Anyway, as you suggested, I added an option to skip wildcards during refresh, along with an option to exclude specific folders.
The latter could be useful if you have normal wildcards you do want to refresh and only want to skip the big collection.
If you update the extension and check that option, the issue should be fixed on your end. It is called `Don't re-scan for wildcard files when pressing the extra networks refresh button`
