### ISSUE TITLE
In some cases, i can't search tags by aliases.

### ISSUE THREAD

**Issue by player99963** [DominikDoom/a1111-sd-webui-tagcomplete#262]
1. Aliases are in Chinese: Although tagcomplete can search for Chinese by attaching a translation file, it can't do so if it's a main file or an extra file. For people who need to create their own tag sets, searching with Chinese aliases will require editing two files at the same time, which can be very inconvenient.
2. The aliases in the extra file are numbers.
3. combination of several tags, e.g. (nose,photorealistic,octane render,photoreal,realism,realistic)

Since I'm not a native English speaker, it's easier for me to use my own language as an alias to search for tags when making my own tagsets.
These are some of the problems I've found while trying, I hope they can be solved.

**Comment by DominikDoom** [comment]
1. Translations can translate both the main tag and aliases. But aliases are supplied as a list for each tag, while translations need to be 1 to 1 since they are treated like a dictionary. So each alias needs its own translation entry, thus a separate file is required.

For custom tag sets you have the following options:
- If you are writing a custom main file:
   - Just write the aliases in chinese. Even if no translation file is selected, it will work to search by the chinese term.
      - For example, the entry `beautiful_face,0,35000,"俏脸"` will be searchable with:
      - ![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/1c8e0418-244b-4e62-8f30-58e816f87470)
      - In this case, "俏脸" is an alias. You can add multiple separated by comma as long as they are enclosed with " "
   - Keep the translations in a separate file, this way you can translate both the main tag and the aliases.
- If you are writing an extra file:
   - Here you can add the translation directly in the last column, since extra files support it for convenience. But since they have no post count and thus no inherent sorting, they are more intended for small custom sets.
   - For example, an extra file entry like this: `beautiful_face,0,My custom tags,"pretty_face,detailed_face",俏脸` will show up as:
      - ![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/c89054fe-fd55-4f00-b065-3daa41155e01)
      - ![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/f0f4874d-cb86-4eda-88a1-8ec0ebdd96eb)
      - ![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/1aa4cfe2-9ac2-4c5b-9f2d-c496aa2dac8e)
     - ![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/52281b34-a511-451a-b117-a0b8bf4247cf)
   - However, with this method you cannot add separate translations for the aliases, it will always translate only the main tag.

2. If at any point translations or aliases show up as numbers, check if the format is correct. Depending on which translation file you use, you might need to check or uncheck this option: 
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/007121ca-2b2a-4c4b-9885-f9559f940582)
As you can see in the examples for point one above, with the correct format aliases and translations for extra tags display just as they would for the main tag set.

3. In theory, it is possible to add groups of tags as a single entry. For example like this as an extra file:
`"(nose,photorealistic,octane render,photoreal,realism,realistic)",0,My custom tags,fav1,现实的`.
That would have the full entry searchable both by terms inside of it, its aliases and its translation:
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/3725f6b8-bc52-4d35-8524-f63890800710)
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/a08e3619-90d7-4463-b6a2-4c7aab07d400)
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/169a1e5f-fae7-469f-b88f-a37034bedda0)

However, as you can see, the list display becomes very crowded like this. The normal method of tag completion isn't really meant for such long groups (although some normal tags can also get very long by themselves).
There are other options for this use case:
- Use the built-in webui styles feature. Normally, this will always be inserted at the end of the prompt, however you can use a placeholder when saving the style: `masterpiece, best quality, {prompt}` will cause the style part (masterpiece, best quality) to be inserted before whatever you add to it. You can also insert the written prompt in between this way.
- Use tag autocomplete's "Chant" feature. This is meant exactly for what you want, it was originally developed by a Chinese user to support prompt starters like those found in the popular 元素法典 series.
   - Sadly the Chinese readme is outdated for this, but you can find the English version here https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/blob/main/README.md#chants to maybe translate it yourself.
   - They use the json format, you can search for them using <c: and with both the name and each of the words listed under "terms". You can take a look at the included demo-chants.json to see how they work. Both the name and the terms could also be in Chinese if you prefer that. The content can be completely separate from the search terms and name, so it is perfect for such style shortcuts.

Hopefully I could answer your questions with this, I believe everything you asked for should already be possible with one of these solutions.

**Comment by player99963** [comment]
Thank you very much for your detailed instructions.
After I retried, I realized that I had made a mistake in the operation and file encoding that caused these problems.

But now I found another situation.
When I search out the tag group of the main file, it will automatically add \ in the tag, such as: \(nose,photorealistic,octane render,photoreal,realism,realistic:1.1\)
The same is not true for tagsets in extra files.
Is this normal? How can I solve this?

Also I know about Chants, but for me it's easier to customize the tagsets directly.

**Comment by DominikDoom** [comment]
The \ is an escape character. As you know, the webui uses () to add emphasis to the terms inside. However, in the standard tagsets some tags already include parentheses by themselves. It's especially common with the format of "character_(series)" to separate characters with the same name from different franchises.
But if the tag would then be inserted as-is, the webui would parse this (series) part as weight parentheses, which will lead to unwanted side effects. \\( \\) tells the webui that we mean the actual parenthesis character there and to not use it for adding weight.

In your case, you actually want it the other way since the tag group in the file includes the weight. Your options for this are either to not include the weighting and brackets in the tag file itself and add it afterwards, or to turn the parenthesis escaping behaviour off in the extension settings. The latter will obviously turn it off for both cases, so if you have any tags that include () in their actual name, you will have to add the \ to them manually. The setting for this is called "Escape parentheses on insertion".

**Comment by player99963** [comment]
I have no more problems, thank you.
