### ISSUE TITLE
Wrong format used for LyCORIS

### ISSUE THREAD

**Issue by DrJimmyBrungus** [DominikDoom/a1111-sd-webui-tagcomplete#263]
I'm not sure if a change was made to Automatic1111 at some point, as I do not use LyCORIS files that often, but here is what I discovered today after wondering why my LyCORIS files seemed to not be working. 

You probably know LyCORIS files can be saved either in the \models\Lora\ folder, or the \models\LyCORIS\ folder. Personally I think it's better to keep them separate and not all mixed up with regular Loras, so I use the dedicated folder.

if you are using the LyCORIS folder, AutoComplete will use the format: <**lyco**:XXX:1>. This no longer seems to work, It should instead be <**lora**:XXX:1>.

If you are using the \models\Lora folder, then AutoComplete correctly inserts them as <**lora**:XXX:1>

This is also regardless of whether you use the LyCORIS filename or its Output name found in its metadata (like what would be used when clicking a thumbnail from the Lora tab)

**Comment by DominikDoom** [comment]
The separat <lyco: prompt format was only ever in use by the third party lycoris extension. As you are probably aware, all of its functionality has since then been integrated into the normal built-in lora extension of a1111, so there isn't a meaningful distinction to be made between them anymore.
The <lyco: qualifier tag autocomplete uses is only for backwards compatibility with the third party extension, so that it will work with webui versions before its integration.

The assumption on my part was that if the separate LyCORIS folder is in use it is because the extension is also still being used (and thus the <lyco: being correct), since I have no real way to check. I haven't really considered your case where you just keep it separate for organization purposes. If you want to keep it that way, I'll add an option to choose which format should be used for files in that folder.

**Comment by DominikDoom** [comment]
I've added a "Use the '<lora:' prefix instead of '<lyco:' for models in the LyCORIS folder" backcompat option. Since I'm assuming usage of current webui versions, it is on by default, so in your case you should have to change nothing.
Models in the lycoris folder will still be listed as Lyco and be searchable with both `<lora:` and `<lyco:`, but when completing always insert as `<lora:` no matter what was used if that option is active.

**Comment by DrJimmyBrungus** [comment]
Honestly, the reason I had my LyCORIS files in a separate folder to begin with is becuase that's what I thought you had to do (why else would there be a separate folder?), and I'd assume a lot of others would be the same.

Nice work with the quick fix once again
