### ISSUE TITLE
Making tagcomplete compatible with wildcard parser-wrap string changes

### ISSUE THREAD

**Issue by NDWaffles** [DominikDoom/a1111-sd-webui-tagcomplete#286]
Had to change 'string to use as wrap for parser wildcard' from __ to ++ in settings, to get dynamicprompts and aDetailer to cooperate.

This came with the cost of tagcomplete not recognizing when I was trying to enter a wildcard with '++'

I was able to figure out a few changes in 'ext_wildcards.js' I could make to make the dropdown for the wildcards themselves, and could get them autocompleted. 
I could NOT figure out what to change to make the dropdown for the wildcard's contents appear. 

My question to you is: Would it be possible to add a field in settings to change 'string to use as wrap for parser wildcard' like in dynamicprompts settings?

Or, more easy: What all would I need to change in .js files to make it so wildcards will display properly with '++' instead of '__'

**Comment by DominikDoom** [comment]
Haven't tried yet, but I think it would be enough to just replace all occurrences of __ in both tagAutocomplete.js and _ext_wildcards.js
The __ prefix isn't used anywhere else but those two files, and only in context of wildcards.
The dropdown for the wildcard's contents is also handled by ext_wildcards.js, but the reason for it not working after your tries is probably that it wasn't recognized as one single tag, which is handled by the main file.

I can add a settings option, but probably won't be able to get to it today. So in the meantime, try just replacing all __ in those files and tell me if it works.

**Comment by DominikDoom** [comment]
It should be fully automatic now, so you can try overwriting your local modifications with the latest version.

There is no TAC-specific setting, instead it just grabs the dynamic prompts setting value if it exists or defaults to "__".
This of course was an assumption on my side that the dynamic prompts extension you talked about was the original https://github.com/adieyal/sd-dynamic-prompts, other extensions that allow the same thing might still be incompatible due to potentially using different option names. Maybe I will change to a separate settings option later if the demand is there, but for now this seemed the most elegant.

There is one thing that will not work automatically with this, which is nested / recursive wildcards. Most of these I've seen directly hardcode the sub-wildcards with the full `__[...]__` format so the parser steps through on its own, but that's of course out of my control since it requires changing the wildcard file contents themselves.
