### ISSUE TITLE
Request: Allows auto completion using the TAB

### ISSUE THREAD

**Issue by uf-hy** [DominikDoom/a1111-sd-webui-tagcomplete#29]
English is not my native language; please excuse typing errors.
When autocompleting tags , I can only seem to use the arrow keys and enter or click the candidate with the mouse, I feel this is not very easy to use.
It might work better if you could just press TAB to complete the first candidate as soon as one is available, and would also be in line with most ides

**Comment by DominikDoom** [comment]
The reason I didn't do that at first is because tab changes the focused element in browsers, so I didn't want to interfere with navigation.
But with the current implementation, the autocomplete window blocks some navigation keys anyway as long as it's open, so I guess it isn't a big deal to allow tab to be used as well.

**Comment by DominikDoom** [comment]
If you selected one with the arrow keys, it will still choose that one on pressing tab, else automatically use the first one like you suggested.
