### ISSUE TITLE
[WebUI Forge] Failed to load module scripts.shared_paths

### ISSUE THREAD

**Issue by Nyksia** [DominikDoom/a1111-sd-webui-tagcomplete#299]
For some reason, with latest update the extension began to fail to load entirely with that specific file.
And weirdly enough, putting a blank `__init__.py` file into the scripts folder fixes the issue, allowing it to import just fine.
Would probably be a good idea to add it to the extension just in case to avoid the issue.

**Comment by DominikDoom** [comment]
This was due to an already fixed bug in forge itself:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1134#issuecomment-2290925628

Putting and __init__.py file forces the extension to be treated as its own module, so the namespace conflict won't occur, but this breaks compatibility and interoperability between extensions if I remember correctly.
