### ISSUE TITLE
[WebUI ReForge] LoRAs/Checkpoints/Embeddings/UI itself are not refreshing/reloading

### ISSUE THREAD

**Issue by Hazitos** [DominikDoom/a1111-sd-webui-tagcomplete#301]
WebUI: ReForge - [f1.1.0dev-v1.10.1RC-latest-1147-g3e80b4d8]
Python: 3.10.0
Torch: 2.3.1+cu121
Gradio: 3.41.2

A month or so ago my UI started to freeze refreshing the LoRAs tab and then eventually the embeddings and checkpoints also did and now I can't even reload the webui, I gotta fully close and reopen it if I want to refresh certain things and I get this tagcomplete message in the dev tools. 

This is the only thing that shows up whenever I refresh anything.
![image](https://github.com/user-attachments/assets/5b18b829-16bf-48aa-a6f8-06745f1396af)

**Comment by DominikDoom** [comment]
The message isn't abnormal, in fact that it appears means at least TAC itself refreshed successfully. As for Lora and the UI itself, TAC listens to the refresh event but just reuses the internal data of the webui, it doesn't (or rather shouldn't) interfere in any way. 

Does it also happen if you disable TAC? If so, it's likely unrelated.

There also is the setting "Don't re-scan for wildcard files when pressing the extra networks refresh button" which I added after a user reported refreshing issues due to their wildcard collection (thousands of files symlinked on a slower external hard drive).

Other than that I can only suggest checking the lora/embedding files themselves, it might be a corrupted file or just the total amount of files being very high causing issues.

**Comment by Hazitos** [comment]
Thing is while I do have quite a number of LoRAs this doesn't seem to be the issue since my friends have even more than me, an about the wildcards thing, while I do hve the extension I have never used it as I don't exactly know how wildcards work.

I did try clicking the TAC refresh button, and it was a while ago now and it's still loading infinitely.
![image](https://github.com/user-attachments/assets/5b89e411-83ab-4649-84f8-253e34b86543)

**Comment by DominikDoom** [comment]
Yeah that's definitely abnormal, it takes max 3 seconds for me with a good amount of loras, embeddings etc.

The amount question was more about extreme cases to make sure, e.g. the user with the wildcard issues I mentioned used a bundle with like 150k wildcards in it. That caused loading issues due to each request trying to parse a 35+ MB file.

Is there anything suspicious in the network tab of the browser dev tools when you start a refresh? For example a request that starts but never returns.

**Comment by Hazitos** [comment]
I didn't notice anything "suspicious" in it, though I don't really know what i'm looking at lol
![image](https://github.com/user-attachments/assets/428e62dd-b9ab-491d-b065-4d1e51adff0c)

**Comment by DominikDoom** [comment]
That was just to get a list of all files TAC reloads after clicking on the refresh, I was hoping to see a culprit from a file not responding or something like that.

There is actually one suspicious thing:
![image](https://github.com/user-attachments/assets/e45a9a57-b3c4-4e07-948a-3e184e137bda)
Pending means the response wasn't received yet. For comparison, this is what it looks like on my end (with 2000+ Loras, ~500 Embeddings and ~150 wildcards):

https://github.com/user-attachments/assets/904afbcc-1190-49b4-a960-deb238a7c6bb


As you can see, the pending "join" resolves relatively quickly - that is also the moment when the refresh in the UI finishes.
The bad news is that join is from webui internals - I have no clue what would cause the issue you experience at the moment.
TAC seems to get all its files normally, for some reason your webui / its gradio backend just doesn't receive answers to its own communication requests.
It might be a somehow corrupted venv, issues with specific files, extension conflicts, etc. Extremely hard to diagnose.

If possible I would suggest trying to reproduce the bug with a minimal setup - delete and let it recreate the venv, TAC as the only active 3rd party extension and renaming the lora or embedding folders to see if a file there might be the issue.

**Comment by DominikDoom** [comment]
Ah, I just noticed the full refresh-temp-files request is unusually long with 12+ seconds, so something is definitely going on there. It might be that the webui times out while waiting for TAC. But still no clue why it takes that long. There must be something related to the files it searches.
How many embeddings/lora do you have, if you can give a rough number? Any symlinks? Slow harddrive, network share, anything like that?

**Comment by Hazitos** [comment]
Embeddings I have about 10, don't use them much, now LoRAs... Surprisingly... I have 713. I did not actually know I had that many lol. I don't know what Symlinks are, my harddrive is slightly slow but good enough and I have no network share.

One tidbit I should add, when I was testing stuff with my friend a couple weeks ago I fully reinstalled my python on another drive to see if anything would change, any nothing did. I also have all my AI-related stuff together in this one 1TB HDD. That refresh_embeddings part was already set to False.

**Comment by DominikDoom** [comment]
That amount should be no problem, like you said. But it's also nothing that warrants the reload taking over twelve seconds.
Even the slowest HDD would be faster than that.

> That refresh_embeddings part was already set to False.

Are you sure? There's a call with false in line 741 which you might've confused it with:
![image](https://github.com/user-attachments/assets/00cb0dfb-5ab3-48e3-8e2a-7b5963e8a6da)
But that other one in line 483 should be true in the current TAC version.

Since you only have 10, I don't think that's the cause, but it doesn't hurt to try.

Other than that, did you already try with the wildcard option off? Even if you don't use wildcards, another extension might've added a lot of wildcard files, so just to make sure it has no impact would be good to know.

**Comment by Hazitos** [comment]
I have had wildcard part enabled for a while now yes and you're right, I had only one of the refresh_embeddings on False, I hadn't seen the 483 one, I'll test it right now.

**Comment by Hazitos** [comment]
Okay man, after changing both refresh_embeddings to False, everything is refreshing just fine, even faster now. Thank you very very much for going so far to help me!

**Comment by DominikDoom** [comment]
Glad to hear, although I'm still unsure why it would cause that. After all I just pass that parameter to the webui itself.
Anyway, I'll quickly add an actual option for it so you can change this behavior without modifying the code (which would break with updates).

**Comment by Hazitos** [comment]
Also one more thing. This whole issue began, the very same day another issue with Civitai Helper began where it would download stuff like normal but the descriptions would all be broken like this. 
![image](https://github.com/user-attachments/assets/9723ec6d-7cf4-4c09-90d5-5ca50dc81950)

**Comment by DominikDoom** [comment]
Don't think so, that is just an issue with how Civitai Helper shows HTML in this box (or more like that it doesn't).
The "broken" stuff is just the formatting from the civitai website, instead of plain text the author wrote their description in this way to highlight different words with colors or bold text.

**Comment by DominikDoom** [comment]
Alright, you should be able to update throught the webui now and get the "official" fix.

After considering for a bit, I made it off by default, with the option being to restore the old behavior with force=True. So in your case you don't need to change anything with the new setting.

**Comment by Hazitos** [comment]
> Don't think so, that is just an issue with how Civitai Helper shows HTML in this box (or more like that it doesn't). The "broken" stuff is just the formatting from the civitai website, instead of plain text the author wrote their description in this way to highlight different words with colors or bold text.

It's like that with everything I download through civitai helper though, same thing is happening with my friend.

**Comment by Hazitos** [comment]
This is how it's supposed to be formatted, all of the ones downloaded from before these issues began are like this.
![image](https://github.com/user-attachments/assets/7691bf94-c254-41ed-812a-cf6468574414)

**Comment by DominikDoom** [comment]
Definitely a change on Civitai helper's side, also happens with the base webui. I guess its default behavior just coincidentally changed around the same time.

Civitai Helper has this option you can check:
![image](https://github.com/user-attachments/assets/a03ac2c8-3a3f-4553-b17f-ffd0ae589233)
which will convert it to plain text.

**Comment by Hazitos** [comment]
> Definitely a change on Civitai helper's side, also happens with the base webui. I guess its default behavior just coincidentally changed around the same time.
> 
> Civitai Helper has this option you can check: ![image](https://private-user-images.githubusercontent.com/34448969/364551547-a03ac2c8-3a3f-4553-b17f-ffd0ae589233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0ODUzMTgsIm5iZiI6MTcyNTQ4NTAxOCwicGF0aCI6Ii8zNDQ0ODk2OS8zNjQ1NTE1NDctYTAzYWMyYzgtM2EzZi00NTUzLWIxN2YtZmZkMGFlNTg5MjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDIxMjMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxN2NmNTIwMjZjN2E4ZjZiNzYwNjkyZTE5NWQwMjAyNmJmYmFhZGZmNjIzMTI0MmNjMWEyYzM3MzNhODU5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vsyL5H5gIuxdYd9vWYsL4zU1c94hQwa8K5cocpNCuLo) which will convert it to plain text.

Me and my friend both tried that and it didn't do anything with or without it, so it's an issue on their end.

**Comment by DominikDoom** [comment]
It will only change it for new downloads, descriptions for existing models come from a json file next to the model on your disk and won't get modified automatically.
