### ISSUE TITLE
Backslash ( \ ) in chants.json breaks the chant feature

### ISSUE THREAD

**Issue by blue-popsicle** [DominikDoom/a1111-sd-webui-tagcomplete#307]
Some chants I want to put in the chants.json file need to include the backslash ( \ ) character due to tags which include parentheses.

However, putting a backslash anywhere in the chants.json file breaks the Webui's ability to load any chants at all. 

Seems to be another broken sanitization rule similar to Issue #267

**Comment by DominikDoom** [comment]
The loading and sanitization is fine, I think your issue is rather not escaping the char in the JSON itself.
`\` is an escape sequence marker, so writing `\(` in JSON will be invalid. It expects an actual sequence like `\n` (newline) or `\"` to escape a double quote inside the string. For a literal `\`, you have to double it: `\\`.

To summarize:
- `artoria_pendragon_(fate)` Default
- `artoria_pendragon_\(fate\)` Invalid JSON syntax, will break the file
- `artoria_pendragon_\\(fate\\)` Works and will output what you expect

I would recommend editing JSON in an editor with syntax highlighting, e.g. VSCode:
![image](https://github.com/user-attachments/assets/9d92f47d-d013-4d3c-b905-1c42b5efb859)
![image](https://github.com/user-attachments/assets/0a6fb746-a594-452f-ada6-ec71edabe3cc)
Or Notepad++:
![image](https://github.com/user-attachments/assets/b2cef8d4-83ed-423e-bad8-4c9441a0a4d7)

That will make spotting such errors easy.

**Comment by blue-popsicle** [comment]
Ahhh, I see, that makes sense. Thank you for the explanation!
