### ISSUE TITLE
danbooru.csv update 2024-11-9

### ISSUE THREAD

**Issue by yamosin** [DominikDoom/a1111-sd-webui-tagcomplete#309]
i made a updated danbooru.csv by danbooru api, then import aliases from old danbooru.csv and aliases.json from danbooru api
removed tags with counts below 30, same as the original danbooru.csv, which I assume is for performance reasons?
I'm not sure if it's right to upload it here, and hope it helps someone who needs it
[danbooru_tags_2024-11-9.csv](https://github.com/user-attachments/files/17684561/danbooru_tags_2024-11-9.csv)
![image](https://github.com/user-attachments/assets/f4e38ba9-68c2-4843-a0fc-ea53f769d479)

**Comment by DominikDoom** [comment]
I'm fine with replacing the current tags with your version, just one suggestion:

Tags without aliases in your version have `","` as their alias column, and also a trailing comma if there are aliases filled in. That's pretty much just wasted space. If there are no aliases, the last column can be completely empty after the CSV comma. It would be nice if you can remove those. You could also create a [pull request](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/pulls) if you'd like to update it that way.

---

> removed tags with counts below 30, same as the original danbooru.csv, which I assume is for performance reasons?

Yeah, performance and quality of autocomplete results. A lot of these low count tags are mostly useless for prompting since they are often times names of lesser known artists, their OCs, or duplicates not yet properly linked / aliased to the actual tag. Not a lot of models (if any) will have learned those properly from the limited training material. The cutoff I used is just the top 100k results by the way, not a specific post count. But since a lot of the lower tags have the same post count, that might be a bit arbitrary.

**Comment by yamosin** [comment]
> I'm fine with replacing the current tags with your version, just one suggestion:
> 
> Tags without aliases in your version have `","` as their alias column, and also a trailing comma if there are aliases filled in. That's pretty much just wasted space. If there are no aliases, the last column can be completely empty after the CSV comma. It would be nice if you can remove those. You could also create a [pull request](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/pulls) if you'd like to update it that way.
> 
> > removed tags with counts below 30, same as the original danbooru.csv, which I assume is for performance reasons?
> 
> Yeah, performance and quality of autocomplete results. A lot of these low count tags are mostly useless for prompting since they are often times names of lesser known artists, their OCs, or duplicates not yet properly linked / aliased to the actual tag. Not a lot of models (if any) will have learned those properly from the limited training material. The cutoff I used is just the top 100k results by the way, not a specific post count. But since a lot of the lower tags have the same post count, that might be a bit arbitrary.


<html  xmlns:o="urn:schemas-microsoft-com:office:office"  xmlns:x="urn:schemas-microsoft-com:office:excel"  xmlns="http://www.w3.org/TR/REC-html40">
<head>

<style>

</style>

</head>
<body>


1girl | 0 | 5882641 | 1girls,sole_female
-- | -- | -- | --
highres | 5 | 5099314 | high_res,high_resolution,hires
solo | 0 | 4899585 | female_solo,solo_female
long_hair | 0 | 4250048 | /lh,longhair
breasts | 0 | 3361773 | /b,boobs,breast,breats
commentary_request | 5 | 3239940 | /com
looking_at_viewer | 0 | 3232756 | pov_eye_contact
blush | 0 | 2879847 | blushing,flush,flushed
smile | 0 | 2803771 | :),:},smiling
open_mouth | 0 | 2305567 | mouth_open
short_hair | 0 | 2213871 | short-hair,shorthair
simple_background | 0 | 1764114 | /simplebg
shirt | 0 | 1754636 | shirt_only,shirts
blue_eyes | 0 | 1724465 | blueeyes,light_blue_eyes
absurdres | 5 | 1718326 | insaneres,very_high_resolution
large_breasts | 0 | 1544154 | big_breasts,large_boobs,large_breast,large_tits
skirt | 0 | 1524462 |  
long_sleeves | 0 | 1520053 | long_sleeve
blonde_hair | 0 | 1505468 | blond,blond_hair,blonde,blondehair
multiple_girls | 0 | 1501239 | /ngirls



</body>

</html>

Yay, clearing unwanted stuff, makes sense, I just tested it before and thinking I couldn't feel the impact so just let it go, and now that I've cleaned up column C with a regular expression, it's clean now
Please feel free to take it and update it as you want, I'm not a programmer and have very little knowledge of github and am not familiar with the functions associated with PR lol
[danbooru_tags_2024-11-9_fixed.csv](https://github.com/user-attachments/files/17687893/danbooru_tags_2024-11-9_fixed.csv)

**Comment by DominikDoom** [comment]
Thanks, I merged it in. Your regex left a few `""` which I removed too, so now it's really the minimum.
