### ISSUE TITLE
Request: Scrollable tag lists (no, not a dupe of #27)

### ISSUE THREAD

**Issue by byzod** [DominikDoom/a1111-sd-webui-tagcomplete#34]
As non-native english speakers, we're not sure what we want or the exact spelling at most of the times, that's why `showAllResults` is set to `true` by default in chinese translate version

The typical usage is, user type few characters they remember and scroll down hundreds times to find out the exact word they want, or google if not found then

So the dropdown list with many result would be more convenient to use by supporting scroll actions (page up/page down/home/end)

**Comment by DominikDoom** [comment]
So, just to make sure I understand correctly, this is only about supporting the extra hotkeys you mentioned for scrolling with the keyboard, right?

**Comment by byzod** [comment]
> So, just to make sure I understand correctly, this is only about supporting the extra hotkeys you mentioned for scrolling with the keyboard, right?

Yes, or similar feature that can pick result quickly

Actually `page up/down/home/end` is not a perfect solution since this can't be done with left hand only...but I didn't think of a better way

**Comment by DominikDoom** [comment]
Alright, I'll add them later today.
By how much should page up/down scroll? Arrow up/down currently goes down by one, so should Page up/down just go like 5 at once to scroll faster? (I can't use the browser's scroll amount since the list technically isn't focused while selecting)

> Actually page up/down/home/end is not a perfect solution since this can't be done with left hand only...but I didn't think of a better way

Yeah with left hand accessible keys I can't think of anything either except just using the mouse.
