### ISSUE TITLE
performance issues with wildcards

### ISSUE THREAD

**Issue by djkacevedo** [DominikDoom/a1111-sd-webui-tagcomplete#38]
With a lot of wildcards performance drops massively.

I got it turned off for now, and works fine with regular tags.

I'm using the wildcards from the dump on https://rentry.org/sdupdates so 483.

More than a dozen slows things down, more than a couple hundred makes the webui unusable.

**Comment by DominikDoom** [comment]
I've reproduced the issue with those tags, I'll see what I can do about it.

**Comment by DominikDoom** [comment]
I think I found the issue:
Despite the total number of wildcards being much less than the number of tags, it caused substantial memory issues due to how they were stored. Currently, I match files to their contents with a typical key-value structure, which seems to be the issue here.

I changed wildcards to be loaded on demand instead of pre-matched to their respective files, so I could store them without keys. This makes it take minimally longer for small wildcard file counts since they're not preloaded, but it's barely noticeable and fixes the loading & performance issues for large amounts.
