### ISSUE TITLE
feature request: extension installation

### ISSUE THREAD

**Issue by Akegarasu** [DominikDoom/a1111-sd-webui-tagcomplete#41]
add support for install this prog as extension (like wildcards) 
[Extensions](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions)

Now it read tag from web UI installation root folder.

**Comment by DominikDoom** [comment]
I already have it planned, but with the current setup it isn't possible yet since the user can choose the folder name inside extensions themselves. The JavaScript which autocomplete relies on needs to know this name beforehand to access the files in there, which is a bit tricky to do.

I have some ideas I will try when I have time, so I will probably add it this week.
