### ISSUE TITLE
Installed as Extension but it cant find correct directory, Docker

### ISSUE THREAD

**Issue by thojmr** [DominikDoom/a1111-sd-webui-tagcomplete#46]
Hey again!

I installed this project as an extension under the directory `/root/data/extensions/a1111-sd-webui-tagcomplete-main/*` as instructed,  `/root/data` is my webui root.

But I get this error when running the app `RuntimeError: File at path /root/data/tmp/tagAutocompletePath.txt does not exist.`
Not sure why it is searching within the `./tmp` directory?

I am using the latest Automatic1111, and the latest of your code.
I also removed all the old files from your code before installing this one.  Could there be any cached files left around?
Also cleared my cache just to be sure.

Thanks!

**Comment by thojmr** [comment]
Hmm changing 
`with open(FILE_DIR.joinpath('tmp/tagAutocompletePath.txt'), 'w', encoding="utf-8") as f:` 
to 
`with open(TAGS_PATH.joinpath('tmp/tagAutocompletePath.txt'), 'w', encoding="utf-8") as f:` 
AND 
manually adding a `.extensions/*/tmp` folder fixed that error for me, but now I cant get the autocomplete to show at all.
Theres also now a `tmp` folder and a `temp` folder in the same directory.  I did not create the `temp` folder

**Comment by DominikDoom** [comment]
It is looking in the `tmp` folder since the javascript needs at least one file with known and fixed location to load the other files which could be in any folder. So I essentially just create one file that contains the path of the extension installation, like the name suggests (since the user can choose any folder name).
The `temp` folder then is the extension specific folder which is supposed to be created in tags and contains the rest of the found paths, e.g. embeddings and wildcards.

At least on Windows the `tmp` folder gets created by the webui itself to log stderr/stdout. Seems like it doesn't on Linux.
At the moment I don't create it if it doesn't exist like I do with the `temp` folder since I thought the webui does it itself. So that is the reason for the first error.

The second problem is probably due to the tagAutocompletePath.txt being created in the tags folder due to your change, which the js side can't find.
Does it not work if you leave the first change at FILE_DIR but manually add the tmp folder?

**Comment by thojmr** [comment]
It works after manually creating the ./tmp folder in the webui root dir.  So you might want to have your script create that folder if it does not exist for us WSL/linux users.

Thanks!

**Comment by DominikDoom** [comment]
Yeah I'll do that shortly, thanks for the heads up!
