### ISSUE TITLE
[Feature request] make autocomplete suffix (`, `) optional in config file

### ISSUE THREAD

**Issue by byzod** [DominikDoom/a1111-sd-webui-tagcomplete#49]
tagcomplete add comma when select a tag from result unless it's

However there're many situation that comma after a tag is not needed

1. multiple tags in parenthesis for example complete `(wet swimming:1.2)`
2. Some people suppose that even for novelai model, natural sentence works better than tag style when describe background and actions, I feels it's true so I use more natural sentences now, that's when the auto suffix is unnecessary or even bothering
   In this demo I have to press `backspace` many times to write a short sentence
   ![An1](https://user-images.githubusercontent.com/848607/198845210-c99daf28-1972-41f1-93fa-d036717f1c99.gif)

4. The smart detection is limited, `, ` is not added to `(<tag>:<number>)`, but still added to `(<tag>)` or `[<tag>]`, it only works when editing too, writing `(dog ears:1.2)` character by character with tagcomplete you get `(dog ears, :1.2)`
5. It's not needed in editing, change `cat` to `cat ears` in `girl with cat and tail` with tagcomplete 
   the result will be `girl with cat ears,  and tail` (note there are two space after `,`)

**Comment by DominikDoom** [comment]
I'll add a config or UI option for that tomorrow, I've heard multiple times now that some would like to turn it off. Since it comes down to personal preference there's no reason not to have an option for it.
1 and 2 are definitely a valid argument for it as well.

3 and 4 too, although 3 is probably just an oversight which I can add. Similarly 4 with the double space is because it currently always adds comma and space together, I can add a check if there already is a space after the comma which should mitigate that.

**Comment by DominikDoom** [comment]
The way I chose to do it for now is via both config and UI, since I think some users might want to switch this functionality on/off frequently.
So it has its own checkbox:
![image](https://user-images.githubusercontent.com/34448969/198889202-a30c1c8c-12bf-462e-944e-5db397bf8b64.png)
and whether `appendComma` is true or false in the config dictates if it is on or off by default.
