### ISSUE TITLE
Autocomplete not working, generating error in dev console

### ISSUE THREAD

**Issue by houdinii** [DominikDoom/a1111-sd-webui-tagcomplete#5]
I followed the instructions and ensured everything is in it's proper directory, but the autocompletes appear to not be turned on at all. I am receiving this error:

`Cannot read properties of null (reading 'children') TypeError: Cannot read properties of null (reading 'children')
    at updateOnBackgroundChange ((index):773:45)
    at (index):910:5
    at runCallback ((index):82:9)
    at Array.forEach (<anonymous>)
    at executeCallbacks ((index):88:11)
    at MutationObserver.<anonymous> ((index):93:9)
runCallback @ (index):84
executeCallbacks @ (index):88
(anonymous) @ (index):93
`

I'm 99% sure the error is related to the above. I made sure and disabled plugins as well to rule them out.

The plugin "iCloud Passwords", the Apple password manager, breaks this plugin, fyi.

**Comment by DominikDoom** [comment]
The error above isn't related to this script, it's caused by the imageviewer.js file that's shipped with the webui. Happens for me as well while the script is working fine.

Just to make sure - tagAutocomplete.js has to go into the `javascript` folder, not in the `scripts` folder like most other scripts.
Like this:
![image](https://user-images.githubusercontent.com/34448969/195697260-526a1ab8-4a63-4b8b-a9bf-ae0f3eef780f.png)

Another idea:
Since you said the Apple password manager breaks it, are you using Safari? It might be that Safari doesn't support all the features the script uses.

**Comment by houdinii** [comment]
*facepalm. I swear I read that 10 times! I'll give that a try. 

The password manager situation is separate. I'm using Chrome for windows and the error here was:
`Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared`
along with a line number. It's apparently a common issue with autofill scripts and went away when I disabled the Apple plugin.

**Comment by houdinii** [comment]
It works now, you were right about the directory. Thanks!
