### ISSUE TITLE
Feature request, include tag popularity count next to tag name in list

### ISSUE THREAD

**Issue by thojmr** [DominikDoom/a1111-sd-webui-tagcomplete#60]
I think it would be very useful to have the tag count next to the tag name when selecting from the list.  This would allow us to select a tag based on its popularity when there are multiple similar tags to choose from.

Not sure how much extra work that would be though.

**Comment by DominikDoom** [comment]
The coding work in this plugin would be very little, the bigger problem is getting the data.
At least the program I used to build the tag file ([Grabber](https://github.com/Bionus/imgbrd-grabber)) sadly doesn't include the tag count in the offline tag database you can build. So I would have to replicate its functionality using the official API.
It's definitely possible and I agree that it would be useful, but not quick to do for now.

Just for choosing which tag is more popular, it's a lot simpler though: Tags in the default tag files are ordered by count, and since the script doesn't sort them at any point, tags higher in the list will always be more popular than those below. You just can't compare by how much.

**Comment by DominikDoom** [comment]
Small update:
I have found the official danbooru tag dump on its [public cloud console](https://console.cloud.google.com/storage/browser/danbooru_public/data) in the meantime, which contains post count and a few other interesting infos.
I'll have a look at it and see if I can process it to work with the script.

**Comment by byzod** [comment]
There's some tag builder have similar feature on github, for example [this one](https://tags.novelai.dev/), if it helps

**Comment by DominikDoom** [comment]
Yes, exactly. It already works similar to the translation feature, so I think it'll be possible without much reworking. I just need to be careful to not break existing translations.

**Comment by DominikDoom** [comment]
Small preview:
![image](https://user-images.githubusercontent.com/34448969/199820121-eba51ed1-e91b-44f7-8d16-c1aab90ab9cc.png)

At least for danbooru tags the work is almost done, just need to do a bit of cleanup and update how translations are handled. I tried to find similar public tag data for e621 tags, but wasn't able to get anything so far. So I'll have to get them using the API, which will probably take a bit longer.

**Comment by thojmr** [comment]
This has been working great, thanks for the work
