### ISSUE TITLE
Many tags are missing in new `danbooru.csv` including popular ones

### ISSUE THREAD

**Issue by byzod** [DominikDoom/a1111-sd-webui-tagcomplete#64]
For example `black_legwear` and `silver_hair`

![2](https://user-images.githubusercontent.com/848607/200130939-b87d4244-52c2-4c33-986f-8eafa7104c9f.jpg)

![1](https://user-images.githubusercontent.com/848607/200130942-01ff698b-c55f-4706-8526-85c426304625.jpg)

**Comment by DominikDoom** [comment]
This is because those tags were marked as deprecated. When I converted the danbooru tag dump to CSV, I excluded deprecated tags because I thought it meant that the tags were renamed or something like that, but if some have that many images, maybe it makes sense to still include them.

![image](https://user-images.githubusercontent.com/34448969/200131436-3702b865-5d45-4b26-8f16-9ddc9194092c.png)
![image](https://user-images.githubusercontent.com/34448969/200131461-568f33c5-beae-458b-aa2c-56be49a229a4.png)

**Comment by DominikDoom** [comment]
Small note: this will result in minor duplication since for some cases the deprecated tag was replaced by its alias, so both will show up since the old alias is still there.
E.g. in this example, black legware is deprecated but when it was still in use, black pantyhose was an alias for it. So now the script both finds the alias for the old tag and the new tag that isn't redirected anymore. But since they have different post counts, I don't think it's an issue, since models were likely trained on images containing both.
![image](https://user-images.githubusercontent.com/34448969/200131958-c70e62e3-5542-43a3-9c4c-de4d20419e06.png)
