### ISSUE TITLE
Feature Request: Move Autocomplete options to Settings

### ISSUE THREAD

**Issue by Evil-Dragon** [DominikDoom/a1111-sd-webui-tagcomplete#71]
Would it be possible to move:

<img width="228" alt="firefox_WbsWlEq0pV" src="https://user-images.githubusercontent.com/9480613/200762501-fc94cc76-6479-41cc-a971-c2e96b48b998.png">

To have it's own section the settings page in A111? You could also add the other settings from config.json so that you won't have to edit the file manually.

**Comment by DominikDoom** [comment]
Possible yes, but it's pretty annoying since there is no direct way to access the settings in the javascript part. So I'd have to manually extract them from the settings page HTML as far as I know, which is why I used the extra config file and UI settings so far (if anyone knows a better way, please tell me!).
But I do plan to rework the settings system when I have time, since an edited config can also cause problems with updating the extension using the recently added webui tab, like what was asked about in #70.

**Comment by zencyon** [comment]
could the checkbox setting just be moved a little maybe? 

i can see them being handy to have at hand as on/off switches, 
but atm they create a huge deadspace area in an already cramped ui, which already makes me consider it not worth it, even if the autocomplete and everything is perfectly cool :)

example: second picture, or a place they don't create deadspace

![deadspace](https://user-images.githubusercontent.com/43258551/202811301-f097db5b-3f12-431e-a4e2-c572fa886836.PNG)
suggest moving settings somewhere inline, if possible:
![moved](https://user-images.githubusercontent.com/43258551/202811306-81fd9bcd-a09f-4706-8ffa-984b51a2b476.PNG)

**Comment by zencyon** [comment]
@DominikDoom ah, thank you, yes, that help a lot :)
still, having the toggle on/off is nice
don't like restarting webui for it tho, often got several tabs with prompts open
it's not something you use constantly so could be in a less important spot.. can you chose where to place it?
another small spot would be just below the 2 style dropdowns (never use those lol)

**Comment by DominikDoom** [comment]
I'll have a look at it, but since the end goal is to move to real options anyways as soon as I have a bit more time to work on it, a simple inline solution like you said will probably be fine for a while

**Comment by DominikDoom** [comment]
@zencyon I've moved the settings inline for now like you suggested, it should work on all display sizes since the quicksettings bar is using flexbox.

**Comment by zencyon** [comment]
@DominikDoom awesome, i just updated and tried it, cheers <3
cool that it works on various displays too

**Comment by byzod** [comment]
It's worth noting that those spaces are preserved for quick settings

![3](https://user-images.githubusercontent.com/848607/203298460-53bf36c4-aa7a-4bec-b7c0-b3e09430fa45.jpg)
![1](https://user-images.githubusercontent.com/848607/203298423-74446a92-09bd-42eb-ba08-871a7ea36c22.jpg)
![2](https://user-images.githubusercontent.com/848607/203298447-127b0800-1890-43ef-a570-7296e8984b6c.jpg)

**Comment by DominikDoom** [comment]
@byzod 
> It's worth noting that those spaces are preserved for quick settings

I know, that's why I said the user won't be able to change the order as long as it isn't added as "real" settings. But they will be added to the end of the quicksettings list just like any other setting, if there's not enough room flexbox will just put them into the next row like the normal settings.

**Comment by zencyon** [comment]
hey @DominikDoom :) been using the addon a fair bit now, it's great
one thing i notice is that sometimes it sort of locks up the keys and get stuck until you pick an option and then correct the word you were typing. In best case scenario i think it should never be blocking the typing in any way

have you experienced this? 
(not sure if i should make new issue yet, i haven't found a solid reproduction of the issue yet, it just happens sometimes)

**Comment by DominikDoom** [comment]
@zencyon It shouldn't block normal typing keys, the only keys it captures by default are Up & Down arrows to navigate in the results list and a few related ones like Page Up/Down, Home & End. Left and right arrows aren't used by default, so moving with those to correct typos should always work.
As a side note you can always close the pop-up by pressing Escape. If you can reproduce your issue, feel free to open a separate issue for it, sounds unintended.

**Comment by DominikDoom** [comment]
It was a bit of work as expected, but I finally had the time to complete it. Everything except for the tag colors has moved into the normal settings menu. I wrote about it a bit more detailed in #80, but since it is now based on the webui settings you can add the options to your quicksettings bar if you would like to keep them inline.

The rework also brought some nice quality of life improvements, like reloading tags without restarting the webui and selecting them via dropdown.
