### ISSUE TITLE
feature request: handle tag with absurd length

### ISSUE THREAD

**Issue by byzod** [DominikDoom/a1111-sd-webui-tagcomplete#72]
This "bug" looks more like easter egg...a will-take-a-look-when-I-am-boring issue tbh

---

In 4eabf00f015b2ddedba98176752dd853678a6f57, width limit of results are removed, this works fine to check full text of long tags, but there're always exceptions...

[山神ルーシー](https://dic.pixiv.net/a/%E5%B1%B1%E7%A5%9E%E3%83%AB%E3%83%BC%E3%82%B7%E3%83%BC%E8%B2%B4%E7%BE%8E%E5%AD%90%28%E7%95%A5%29) is a normal cute waifu without superpower

But she has onething special: a very long name
![0](https://user-images.githubusercontent.com/848607/200803976-4f00eb51-a0f2-4e4a-8a70-3d11991ada2b.jpg)

This is what happens when you search part of her name (it's too long so I rotated 90 degrees)
(I made translation for it so it's even longer XD
![1](https://user-images.githubusercontent.com/848607/200804531-986ac9f2-95d8-45d0-a16e-e49f6d201a8b.png)

---

A possible way is to limited the maximum width to be as the same as the prompt box at maximum, it's a safe width at all possible situation I think. Then allow new lines for long tags
demo:
![2](https://user-images.githubusercontent.com/848607/200805285-91ee03fa-3807-419a-9d78-be805638b7bb.jpg)

Or cutoff long tags dynamically, only shows part of it. Hovering or something to check the full text.
demo:
![3](https://user-images.githubusercontent.com/848607/200805533-0968ff0b-ff7c-4efd-9ee0-c8aef5139600.jpg)

Not only absurd tags benefits from this, mobile remote users may also found it useful (but who would use this on mobile anyway lol)
![4](https://user-images.githubusercontent.com/848607/200805773-47ffd0c3-6fad-4b6c-9140-c58fa753fbcb.jpg)

...please no, don't remove those tags, it's fun

**Comment by DominikDoom** [comment]
Lol that tag is insane!

Definitely a good point, I thought about line breaks before but personally found it very uncomfortable to read since it doesn't make it easy to see where aliases end and the normal tag begins, at least with the current setup for those. Also not a fan of potentially huge lists with many different heights, which makes the auto scroll on keyboard navigation a lot less smooth since the jumps are bigger and inconsistent.

The in-sentence ellipsis (or at the end) with some way to view the full thing would be a good option, probably with a custom tooltip so it also works with keyboard selection.
Something like 
![image](https://user-images.githubusercontent.com/34448969/200814904-1be76abb-35b7-4863-8e76-420b7c80c886.png)
(ugly CSS hacked together in the browser dev console, but you get the idea)

I would probably prefer that solution, since it doesn't interfere with normal scrolling and also makes it easy to enable/disable by just hiding or not adding that tooltip popup.
