### ISSUE TITLE
Feature Request: Tag Wrapping on Autocomplete

### ISSUE THREAD

**Issue by xodiack** [DominikDoom/a1111-sd-webui-tagcomplete#74]
Would it be possible to have a feature to wrap tags when autocompleting them? 

For example currently it goes "grey_hair"->"grey hair" would a further step to "(grey hair:1)" be feasible as a toggle or config setting?

**Comment by DominikDoom** [comment]
Definitely possible, but I'm not really sure if it would provide a great benefit for quick attention editing.
At least personally, I think using the `Ctrl+🠕 / Ctrl+🠗` hotkeys while having the relevant portion selected is comparably fast and way easier to control, since the user can choose themselves what parts to select.

**Comment by xodiack** [comment]
Oh I wasn't aware of that feature, probably not much point in my request then as you've said.

**Comment by DominikDoom** [comment]
Alright. I'll close this then, feel free to reopen it if you think the hotkeys aren't enough after a while.
