### ISSUE TITLE
[Feature Request] Embeddings support

### ISSUE THREAD

**Issue by univeous** [DominikDoom/a1111-sd-webui-tagcomplete#8]
It will be great if this script can also load embeddings in the folder and auto complete them.

**Comment by DominikDoom** [comment]
Since the Gradio App is running as a local webserver and doesn't expose much for security reasons, I can sadly only load specific files. So I can't scan the embeddings folder for what's inside.
For wildcards I got around this by adding a file that contains the names of all wildcard files the script should attempt to load, but I don't know how useful that would be for embeddings since there are usually more separate files.

As a workaround, you can either add the embeddings in a CSV to use them instead of the booru tags, or use the wildcard functionality. The latter would allow simultaneous use with the normal tags.
But in both cases you would have to manually add all embedding names to the file.

**Comment by DominikDoom** [comment]
To expand a bit on the latter, you would have to create a new txt file in `/scripts/wildcards/`, e.g. `embedding.txt`.
Then in the `/tags` folder, edit the `wildcardNames.txt` file and add `embedding` to it so the script "knows" your file.
If you start typing `__`, the script will suggest all added wildcards, including the new embedding.txt:
![image](https://user-images.githubusercontent.com/34448969/195834359-81052e73-a3c4-4457-9524-7a71cbae44ba.png)
Which on selection would show you all the embeddings added as lines in that file:
![image](https://user-images.githubusercontent.com/34448969/195834530-a09d0692-662e-47ab-95fa-32c76e7315eb.png)
And then you could replace as normal. So it's only one extra step compared to directly typing < and getting an embedding suggestion.

**Comment by DominikDoom** [comment]
Embeddings are now officially supported in the newest version.
They are automatically loaded and will be shown on typing "<" as of 08c10928f8618913260effacfcb28f05437f13db
