### ISSUE TITLE
Allow auto complete in extensions with prompt text boxes

### ISSUE THREAD

**Issue by crackfoo** [DominikDoom/a1111-sd-webui-tagcomplete#83]
Hi, 

Is it possible to extend the auto complete to extensions? Specifically the dataset one:

https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/issues/17

Thanks!

**Comment by DominikDoom** [comment]
Sure, I can add that.

As was said in the other issue I would need to add each text box separately since each needs its own set of listeners etc., but since I'm not familiar with the extension I'm not really sure which fields are relevant.
So it would be a great help if you could tell me which text boxes from that extension you would like to have supported.

**Comment by crackfoo** [comment]
Hi, 

For that plugin the fields where auto complete would be helpfull would be the:

Caption of Selected Image
Edit Caption
Interrogate Result
Edit Tags

Thanks!

**Comment by DominikDoom** [comment]
I've added it for the dataset tag editor extension, and also included base functionality for other extensions to make it easier in the future if needed. Will still require manual id/selector entries for the textboxes, but in a separate, easier to edit file.

One small issue I couldn't work around so far is that the script doesn't recognize which tag you are editing on the first keystroke for pre-filled textboxes like the Interrogate or Caption of Selected Image ones, but that can just be fixed by typing/deleting a second character, so I didn't want to expend too much effort on it.

**Comment by Hexag0nSun** [comment]
> I've added it for the dataset tag editor extension, and also included base functionality for other extensions to make it easier in the future if needed. Will still require manual id/selector entries for the textboxes, but in a separate, easier to edit file.
(Sorry if this will reopen the issue, I'm new to using the social functions of github, or well.. github at all)

Hi! First of all thanks for this extension, amazing work. To the issue at hand: is this new setting supposed to be On by default? I just changed an unrelated setting and upon clicking save, noticed that my console started showing errors. Then I noticed that the now saved Settings page says that this setting has been changed, and I have not touched it.

I don't mind the restart it made me perform, but perhaps it will be problematic for others if they're in the middle of something. And most importantly: is this a bug or how it's supposed to be?

Thanks

**Comment by DominikDoom** [comment]
I can't say if any console errors are related without more detail, but the rest is normal.
This is indeed on by default, and unrelated settings will show as changed when they are saved to your local config.json webui settings file for the first time, regardless if they are different from the default or not.

In other words, if this was the first settings save after a new setting was introduced, it will not actually change anything, just notify that those settings were written to the file. And regardless, "restart required" just means that the settings change for that specific feature will have no effect until restart, not that it will break anything or not apply others.

**Comment by Hexag0nSun** [comment]
Oh cool thanks for the explanation! 
As someone who was silly enough to choose that file that shouldn't be chosen as an extra file, then taking forever to isolate the issue, I'm now trying to be cautious about the settings here lol :)
