### ISSUE TITLE
1.11+ not working for me

### ISSUE THREAD

**Issue by Roshag** [DominikDoom/a1111-sd-webui-tagcomplete#87]
No idea what can be wrong (except for using the same webui folder for almost 3 months), but 1.11.0+ version do not work for me - no "Autocomplete options" under checkpoint selection menu, no autocomplete itselves. Fixed by using 1.10.1 scripts with latest tags (should it look like "amount >> tag"?). There are no errors in console, so I can't say what is broken

**Comment by Blitzarts** [comment]
Hi! dont work for me either, i installed it from the extensions tab, copying the git code, and the old way copying all in the folder, restart nothing, close the cmd prompt and restart, nothing, restart the ui from settings and nothing :c

**Comment by deezee999** [comment]
Same here guys. I hope this is an easy fix.

**Comment by NaughtDZ** [comment]
Me too

**Comment by yamasoo** [comment]
Not work until disable built-in extension  "prompt-bracket-checker", anyone else ?

**Comment by falsonerd** [comment]
It was working normally yesterday, But then I decided to restart my web ui and now it stopped working completely.
I thought it was conflict with other extension, but tried using it sole and still the same issue.

**Comment by Rogal80** [comment]
Hi, same here – it stopped working since last update

**Comment by DominikDoom** [comment]
I can't reproduce this, it's working fine for me on the latest version of the webui.
The biggest change since v1.10.1 is the new settings system, but that works without issues for me.

> no "Autocomplete options" under checkpoint selection menu

@Roshag That needs to be added manually since it now uses the inbuilt settings, you need to add `tac_active, tac_appendComma` to your Quicksettings list in Settings > User Interface. But autocomplete itself should still be active by default.

If you haven't tried yet, please delete and reinstall the extension fresh, maybe some files didn't get updated properly.


> And it's pointing to the wrong folder as well...

@falsonerd the path is relative from the webui root, so it's pointing to the correct spot. This temp file is needed since the user can rename the extension folder however they want, but I can only load files directly in the Javascript, not search for them (Gradio security policy), so I have to read the base path from there.
