### ISSUE TITLE
Handling Exception, and issues when restarting gradio through web-ui

### ISSUE THREAD

**Issue by falsonerd** [DominikDoom/a1111-sd-webui-tagcomplete#89]
### Autotag Build 1.12.1

Getting some exceptions with tag-autocomplete....
When going to settings tab...
https://pastebin.com/XhU5fQ60
At this point tag-autocomplete still works....

And if I change any settings and restart gradio, sometimes this happen.
https://pastebin.com/n3AnU5TC
When this happens it stops working entirely....

Even restarting collab doesn't work now... dunno whats going on.

**Comment by DominikDoom** [comment]
The first seems related to it not correctly finding the folder the extension was installed in, but if that error happens, autocomplete shouldn't work at all, which is why I didn't catch it there. Which colab are you using?

The second seems unrelated to tag-autocomplete, that says that a file was requested that Gradio can't serve (either because they don't exist or because they are outside the webui root, which is forbidden as security measures). Since they are all image files and artist names, that could be related to the inspiration extension or something similar if you're using that as well.

**Comment by falsonerd** [comment]
Apart from auto-tag

https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards
https://github.com/yfszzx/stable-diffusion-webui-images-browser
https://github.com/some9000/StylePile
https://github.com/Zyin055/Config-Presets
https://github.com/animerl/novelai-2-local-prompt

And Collab... https://colab.research.google.com/drive/1USiUuG_QvqSwbrgm6AAKOwRtOae3mxK6?usp=sharing
Personal one I'm using...

**Comment by DominikDoom** [comment]
Yeah the second exception comes from StylePile it seems, https://github.com/some9000/StylePile/tree/main/StylePile/Artists, those are the artist jpg files it can't find for whatever reason.

Thanks for the colab link, I'll set up my own copy and see if I can reproduce it.

**Comment by DominikDoom** [comment]
Likely the gradio restart messing something up, or quirks of gradio on colab in general.
I just tried it myself, and I also got the first exception, but immediately after opening the webui URL, not after applying settings.

Notably, however, everything related to autocomplete still worked for me, despite the supposed file not found errors.
It seems to me like the files were for whatever reason requested before being ready to serve by gradio, but since it still worked for me maybe it retried? Idk to be honest.

Reloading gradio in the settings created a new share link for me, so the old page was stuck on `Loading...` forever, the new one worked though (without throwing any errors).

**Comment by falsonerd** [comment]
Something along these steps is breaking it , (mainly applying settings)....
1 - Install basics + auto-tagcomplete
2 - start web ui
3 - Tags working fine
4 - go to settings tab and click apply
![image](https://user-images.githubusercontent.com/50148645/208486105-4cbb5f64-a84f-4dc4-a58d-5e45d4dbf6a1.png)
5 - restart gradio
6 - tags stops working

**Comment by DominikDoom** [comment]
Are you restarting gradio using the colab or with the button in the webui settings?

**Comment by falsonerd** [comment]
Web-ui settings

**Comment by falsonerd** [comment]
Changed settings:
![image](https://user-images.githubusercontent.com/50148645/208487239-d87823bb-3bc2-42b6-a1e6-b60c4b4024e1.png)
![image](https://user-images.githubusercontent.com/50148645/208487303-c667920a-b57b-4a5f-80c7-abdcec2e9e48.png)
![image](https://user-images.githubusercontent.com/50148645/208487364-dea0e2ea-54b0-41db-a46e-4ef8b7daf921.png)
![image](https://user-images.githubusercontent.com/50148645/208487424-d2acf3a0-b4c9-43d7-a41c-972f4618ad73.png)
![image](https://user-images.githubusercontent.com/50148645/208487518-55b0ead2-7821-4d43-8617-3a70f6cc3ee5.png)
![image](https://user-images.githubusercontent.com/50148645/208487628-0123da9d-bb1b-4525-a6fb-85635b8d2969.png)
Restarting gradio now....

**Comment by falsonerd** [comment]
After opening new gradio link...
tag wasn't working, after a couple seconds the page hang/froze

**Comment by DominikDoom** [comment]
I tried following your steps but apply & restart didn't make a difference and didn't throw an error.
Interestingly the first exception only happens for me when I click on the share link right after it shows. If I just wait a few seconds before opening it, so far it has never reappeared.

> tag wasn't working, after a couple seconds the page hang/froze

Don't use e621 as extra tags, that functionality is primarily to add small sets of custom tags or new aliases. It will perform an alias match search, so if the extra file is too big, it will take ages to finish. It searches every potential alias for every tag, so in case of danbooru as the main file and e621 as extra, this means 10,000,000,000 (yes, ten billion) lookups. This is why it hangs.

**Comment by falsonerd** [comment]
I was about to write about it, maybe that's the cause...
I though it was extra tags.

**Comment by DominikDoom** [comment]
> I though it was extra tags.

Yeah it is a bit unclear, I'll add a warning for it.
e621 is a completely different main tag set for models trained on the site of the same name, mainly furry models.

Other than that I couldn't find any issues trying stuff out the colab. The original exceptions seem to both be gradio quirks that don't actually break functionality as far as I could see. And as I said they both didn't reappear if I wait a bit before accessing the webui, so it might literally be that the gradio backend isn't fast enough when sharing from colab and needs a bit of warm-up time, so to speak, to serve all the files. Same for the StylePile artist pictures, the faster I opened the page, the more were not loaded correctly. Long startup time might be just related to what CPU colab gave you and what your network speed is, since on colab the tag files need to be accessed over the internet instead of loading them from a local file, which can obviously be much slower depending on connection quality.

**Comment by falsonerd** [comment]
I see thanks for the support.
Main issue for me was actually e621 which was breaking everything due to zillions of tags to load and collab limitations...
so I assumi with e621, assuming I'm using the model...
Should I load only the e621.csv, or both danbooru.csv and e621.csv can be used together, assuming I have a fairly decent cpu?

**Comment by DominikDoom** [comment]
> so I assumi with e621, assuming I'm using the model...
Should I load only the e621.csv, or both danbooru.csv and e621.csv can be used together, assuming I have a fairly decent cpu?

If you are using a furry model like yiffy, you should only use e621 as the main tag file, while for most anime models danbooru is usually a better fit. At least for the models I know of none were directly trained on both, and merges with different tag sets usually result in subpar results as well.

There currently isn't a way to use multiple files as main tags. Extra file just adds them to the bottom, so sorting will also not be correct. I might add that functionality later or do a manual merge of the two csvs, but since not a lot of models would benefit from it I didn't see the need so far.

Btw, I didn't try it on the colab, but at least on local tag-autocomplete also supports tag hotswap, so if you change the file in the settings or add `tac_tagFile` to the quicksettings, it should auto-reload without needing to restart (I noticed I would sometimes need to click on "Apply settings" twice for it to register the change).
