### ISSUE TITLE
Feature request: Embeddings etc.

### ISSUE THREAD

**Issue by Flonixcorn** [DominikDoom/a1111-sd-webui-tagcomplete#97]
when autocompleting embeddings, show embedding version or sort by version, so 2.X vs 1.X and when then selecting the autocomplete delete the <> from front and back :), thanks great embed!

**Comment by DominikDoom** [comment]
It was a bit hacky to get working, but I think it's functional now.
The default list includes both types since I can't test during completion which type of model the user currently uses, but you can prefix the search with v1/v2 to only show those types, as seen below:

https://user-images.githubusercontent.com/34448969/210187734-c2e2292c-7649-4df6-b787-2b2195ab3a29.mp4

I wait for the webui to load the embeddings to then get their version info, but if the model doesn't load any (e.g. a v2 model, but the user has no v2 embeddings, or the same with v1), I can't test what version they are and default to v1 since it's more common.
I could theoretically check them manually, but that would mean embeddings being loaded twice which would increase startup time, so I compromised here.

**Comment by Flonixcorn** [comment]
This doesnt work for me somehow!

**Comment by Flonixcorn** [comment]
https://github.com/tkalayci71/embedding-inspector

here this guy here knows what version the embeddings are at all times!
if that helps somehow

**Comment by DominikDoom** [comment]
Your webui needs to be updated to use it since my method relies on info only introduced yesterday. I do the same as the other guy, compare the vector sizes. Only difference being that I wait for the webui to load them itself to prevent duplicate loading.
